### ISSUE TITLE
[SVE] Test_TC_CADMIN_1_4, Test_TC_CADMIN_1_6 and Test_TC_CADMIN_1_16 are making non-spec-supported assumptions

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#10]
From chip-test-scripts created by [bzbarsky-apple](https://github.com/bzbarsky-apple): CHIP-Specifications/chip-test-scripts#663  

## Description:
These tests are using RemoveFabric to have a fabric remove itself, then expecting a success response.  The spec does not guarantee a success response in this situation, or indeed any response.

## Steps to reproduce:
Run Test_TC_CADMIN_1_4 or Test_TC_CADMIN_1_6 or Test_TC_CADMIN_1_16 against an implementation that does not manage to send out a response before the fabric is removed, which is perfectly well allowed by the spec.

See also https://github.com/project-chip/connectedhomeip/issues/29284

**Comment by raju-apple** [comment]
This step in YAML doesn't do any response check, by default test runner considers response as SUCCESS (1). 
To my knowledge I don't see a way in yaml to check "no response". @bzbarsky-apple can you help me with this? 
Incase if there is no way check this in yaml, only left option is to make a prompt.

**Comment by raju-apple** [comment]
That's really a question for @vivien-apple ...  Ideally, the YAML would allow either success or timeout here as success conditions.

**Comment by manjunath-grl** [comment]
.Fixed in PR [29883](https://github.com/project-chip/connectedhomeip/pull/29883) please verify and close the ticket.
