### ISSUE TITLE
[TC-ACE-1.6] Script has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#100]
## Description:
Below mentioned steps has to be updated in YAML script:

- **Step 2** - Label has to be updated as per the latest test plan.
- **Step 5** - Label and values has to be updated as per the latest test plan.

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [31312](https://github.com/project-chip/connectedhomeip/pull/31312) verify it and close the ticket.

**Comment by KishokG** [comment]
@manjunath-grl Issue not resolved in this PR https://github.com/project-chip/connectedhomeip/pull/31312
