### ISSUE TITLE
Script has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#103]
## Description:

- **TC-TSUIC-1.1:** Step 5 and 7 has to be updated as per test plan.

**Comment by manjunath-grl** [comment]
@KishokG TC_TSUIC_1.1 fixed in PR [31365](https://github.com/project-chip/connectedhomeip/pull/31365) verify it and close the ticket.

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32659

**Comment by KishokG** [comment]
Issue fixed
