### ISSUE TITLE
[Matter1.2 TH] [TC-SM-1.2] Step 6, throwing unexpected error.

### ISSUE THREAD

**Issue by panshaoem** [project-chip/matter-test-scripts#105]
## Description:  
When verifying the Aggregator device, it always throws an "AttributeError: 'list' object has no attribute 'update'".

## LOG:  
[python test.log](https://github.com/project-chip/matter-test-scripts/files/13948253/python.test.log)
[chip-bridge-app.log](https://github.com/project-chip/matter-test-scripts/files/13948254/chip-bridge-app.log)

**Comment by panshaoem** [comment]
I have tried the update and found that I still need to update the following code to fix this test script. Please confirm. Thank you.
![image](https://github.com/project-chip/matter-test-scripts/assets/103939095/ac76972c-6c15-499c-916d-018d5006421a)

**Comment by manjunath-grl** [comment]
@panshaoem Could you kindly attempt the following approach and let me know it works or not. In line [557](https://github.com/project-chip/connectedhomeip/blob/9bde93872fbd16174fdf07c893f56992fdc00352/src/python_testing/TC_DeviceBasicComposition.py#L557), define `sub_children as a set`, and in line [559](https://github.com/project-chip/connectedhomeip/blob/9bde93872fbd16174fdf07c893f56992fdc00352/src/python_testing/TC_DeviceBasicComposition.py#L559), include the second argument as `self.endpoints[endpoint_id]`.

**Comment by panshaoem** [comment]
> @panshaoem Could you kindly attempt the following approach and let me know it works or not. In line [557](https://github.com/project-chip/connectedhomeip/blob/9bde93872fbd16174fdf07c893f56992fdc00352/src/python_testing/TC_DeviceBasicComposition.py#L557), define `sub_children as a set`, and in line [559](https://github.com/project-chip/connectedhomeip/blob/9bde93872fbd16174fdf07c893f56992fdc00352/src/python_testing/TC_DeviceBasicComposition.py#L559), include the second argument as `self.endpoints[endpoint_id]`.

@manjunath-grl Still throwing unexpected error 
<img width="737" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/18e2dfed-db19-406c-80b1-1acf40381174">

**Comment by panshaoem** [comment]
@manjunath-grl 
Could you please confirm if my updates are correct?
1. In line 557, define `sub_children` as a set  
2. In line 559, include the second argument as `self.endpoints`  
3. In line 560, swap the positions of the parameters `sub_children` and `self.endpoints[endpoint_id][Clusters.Descriptor][Clusters.Descriptor.Attributes.PartsList]`

**Comment by cecille** [comment]
The last line should not be swapped. If you DON'T swap the last line and run against the bridge app, you will see failures on the feature map. This is because the bridge app does not correctly implement the feature map. It is a genuine failure.

**Comment by cecille** [comment]
oop, nope, I'm mistaken. You are correct about line 560

**Comment by cecille** [comment]
https://github.com/project-chip/connectedhomeip/pull/31644 for fix
