### ISSUE TITLE
[TC-OO- 1.1, 2.1] Yaml Script has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#120]
### Description:
   

- [ ]    TC-OO-1.1 - `ClusterRevision` value has to be updated as per Test plan . It should be `6` instead of `5`.
                             - Script missed to validate the `OFFONLY` feature in FeatureMap list.

- [ ]    TC-OO-2.1 - In Test Plan New Steps has been added for verifying Write Functionality of the `OnTime` and `OffWaitTime` attributes. So Script has to be updated accordingly.

### Steps to reproduce:
 TC-OO-1.1 - Step 2
 TC-OO-2.1 - Steps 5, 6, 7, 9, 10, 11

### Test Plan References:
   - https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/onoff.adoc

### Yaml- References:
   - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OO_1_1.yaml
   - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OO_2_1.yaml

**Comment by abeck-whirlpool** [comment]
PR https://github.com/project-chip/connectedhomeip/pull/32001
