### ISSUE TITLE
[TC-LTIME-3.1] User Prompt has to be updated as per Verification Step document.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#122]
### Description:
   TC-LTIME-3.1 - In Step 9 Command and log has to be updated as per Verification Step document.

### Steps to reproduce:
Step 9

### Yaml- References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/0589a669-c307-4cf5-aae0-e235f26322a9)
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LTIME_3_1.yaml

### Verification Step document References:   
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/c45e6e9c-221d-4be2-bc70-f55145f5d2d0)

**Comment by gvargas-csa** [comment]
This issue has been addressed in this branch https://github.com/gvargas-csa/connectedhomeip/tree/Modified_yamls_matter_1_3
