### ISSUE TITLE
[TC-IDM-1.3] The command has to be revised as per the chip-repl. 

### ISSUE THREAD

**Issue by Survensa** [project-chip/matter-test-scripts#124]
## Summary Title: 
    The commands mentioned in the YAML seems to be not working, which has to be revised. 

## Description:
    

https://github.com/project-chip/matter-test-scripts/assets/95559513/1c35fd9b-ad5e-4010-9514-c96cfdabffb5

## Steps to reproduce:

-     Build the environment : `scripts/run_in_build_env.sh './scripts/build_python.sh --install_virtual_env out/venv -d true'`
-     Open Repl shell : `chip-repl`
-     Bring up the sample app the other side
-     Provide the commissioning command in repl shell : `devCtrl.CommissionOnNetwork(0x12344321, 20202021)`
-     Try running the following command in the TC_IDM_1.3.yaml  

## Additional Info:
    Not sure either the command in yaml has to be modified or SDK has to be modified.

**Comment by Survensa** [comment]
@tehampson Please look into this issue.

**Comment by tehampson** [comment]
Thanks for reporting the issue https://github.com/project-chip/connectedhomeip/pull/31796 will fix the issue.

The 3 fixes are:
* The issue with the batch command is that I missing a  `)` at the very end. This was likely a copy paste error on my part, Sorry
* As you already discovered `SendCommands`  needs to that that final `s` removed. It should be `SendCommand`
* `name Cluster not defined`. If you do `import chip.clusters as Clusters` after starting chip-repl you should have no more issues. To make the example command more resilient I changed the all `Clusters.` to `chip.clusters`, that way the import is no longer needed

If you'd like to give the updated yaml a try please let me know if you run into any other issues

**Comment by tehampson** [comment]
I cannot mark this as fixed, but it should be fixed now with the latest instructions

**Comment by tehampson** [comment]
@Survensa can you please confirm that the latest update that includes https://github.com/project-chip/connectedhomeip/pull/31796 does fix this issue for you. If so please close the issue
