### ISSUE TITLE
[TC-CNET-4.22] Script has to be updated as per VS changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#125]
## Description:

- In TC-CNET-4.22, the Log has to be updated as per VS changes for test steps 1, 3, and 5.

## Steps to reproduce: 1, 3, 5

**Script Snapshot:**

![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/01a37bce-3ffa-4bbe-8371-7d99459c7395)

**Expected:** Via the TH (chip-tool), verify:

**Comment by gvargas-csa** [comment]
This issue has been addressed in this branch https://github.com/gvargas-csa/connectedhomeip/tree/Modified_yamls_matter_1_3
