### ISSUE TITLE
[TC-OTCCM-1.1, 2.1] Yaml script has to be updated as per Test plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#126]
### Description:

- [ ] **TC-OTCCM-1.1** 

-  Step 3  - In Test plan there is no features in feature map list, But Script is verifying the "OTCCM.S.F00(DEPONOFF)" feature.
-  Step  4c - In Test Plan there is no Feature dependent attribute(DEPONOFF) attribute in AttributeList, But Script is verifying OnMode(0x0003) attribute.

**Test Plan References:**
-  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_oven.adoc

**Yaml References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OTCCM_1_1.yaml

- [ ] **TC-OTCCM-2.1**

- In Steps 5, 6, 9, 10 `OTCCM.S.M.CAN_MANUALLY_CONTROLLED` PICS has to be added.
- In Step 8 CurrentMode attribute value response is Wrong, It should be same as value in the Step 3, But Script is verifying response value should be same as step 6. So Script has to be updated as per Test Plan

**Test Plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_oven.adoc

**Yaml References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OTCCM_2_1.yaml

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32116
