### ISSUE TITLE
[TC-DRLK-2.1] PICS has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#128]
## Description:
In **TC-DRLK-2.1**, `Step 13a` PICS has to be updated in script as per test plan changes`(From DRLK.S.F0b && DRLK.S.A0015 to DRLK.S.F0b && DRLK.S.A0016)`.

**Steps that require to review:** Step - 13a

**Script Reference:**

![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/0aa7ea8a-b716-42a5-bd33-ccc34df825cc)

**Test Plan Reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#tc-drlk-2-1-attributes-check-dut-server

**Comment by gvargas-csa** [comment]
This issue has been addressed here is the branch https://github.com/project-chip/connectedhomeip/commit/86f5c939fec0a753dbd74a197d0a2d78b5751874

**Comment by KishokG** [comment]
Issue fixed
