### ISSUE TITLE
[TC-LCFG-2.1] Script has to be updated as per per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#129]
### Description:
TC-LCFG-2.1 - In Step 1a, 3 `SupportedLocales` attribute PICS has has to be updated as per Test Plan.

### Steps to reproduce:
Step 1a, 3

### Yaml References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LCFG_2_1.yaml

![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/04612d71-3c7f-43cd-bafd-9d5b46d006de)

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Localization.adoc#test-procedure-1
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/815bd7d7-8c4c-47f0-876e-0f6481a283ab)

**Comment by gvargas-csa** [comment]
This issue has been addressed in this branch https://github.com/project-chip/connectedhomeip/commit/c93e7374604fc75cf42e472585d7f49bdebc23ae
