### ISSUE TITLE
TC-IDM-10.1 regular python script fails to account for duplicate values. DeviceBasicComposition script does catch error. 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#13]
From chip-test-scripts created by [CoekaertsJasper](https://github.com/CoekaertsJasper): CHIP-Specifications/chip-test-scripts#674  

## Summary Title: 
    SVE 1.2 TC-IDM-10.1 regular Python script fails to account for duplicate values. DeviceBasicComposition script does catch the errors.

## Description:
   When reading attributes the IDM-10.1 Python script does not check for duplicate values in global attributes. This allows DUTS with these errors to pass. On the other hand, the DeviceBasicComposition version of the script does catch duplicate values correctly. 

## Steps to reproduce:
    Run TC_IDM_10_1.py on a DUT that contains duplicate values in a global attribute. It will not catch the error and PASS the test case. 

## Logs:
    
[TC_IDM_10-1_Lock_Python_DeviceBasicComposition_log_FAIL.txt](https://github.com/CHIP-Specifications/chip-test-scripts/files/12738105/TC_IDM_10-1_Lock_Python_DeviceBasicComposition_log_FAIL.txt)
[TC_IDM_10-1_Lock_Python_log_PASS.txt](https://github.com/CHIP-Specifications/chip-test-scripts/files/12738106/TC_IDM_10-1_Lock_Python_log_PASS.txt)

## Additional Info:
    /

**Comment by cecille** [comment]
For SVE, the request was to use both of these scripts to verify all the test conditions. https://github.com/project-chip/connectedhomeip/pull/29566 consolidates these tests and removes the duplicates script.
