### ISSUE TITLE
[TC-LWM-3.1, 3.3] PICS has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#130]
### Description:
 **Yaml  Script has to be updated as per Test plan for below test cases**
- [ ] **TC-LWM-3.1**
-  PICS has to be updated as per Test plan for all Steps.
-  High level PICS has to be updated as per Test Plan.

- [ ] **TC-LWM-3.3**
- In Step 8 PICS has to be updated as per Test Plan.
- High level PICS has to be updated as per Test Plan.

### Steps to reproduce:

- TC-LWM-3.1 - All Steps
- TC-LWM-3.3 - Step 8

###   Yaml References:

 -  https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LWM_3_1.yaml
 -  https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LWM_3_3.yaml
    
###  Test Plan References:

  -  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_laundry_washer.adoc

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32116
