### ISSUE TITLE
[TC-DISHM- 1.1, 3.1, 3.3] Yaml Manual Script has to be updated

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#132]
### Description:
 **Yaml Manual Script has to be updated as per Test plan for below test cases**

- [x] **TC-DISHM-1.1**
- In Steps 3, 4 comment has to be updated as per Verification Step document.

- [x] **TC-DISHM-3.1**
-  PICS has to be updated as per Test plan for all Steps.
-  High level PICS has to be updated as per Test Plan.

- [x] **TC-DISHM-3.3**
- In Step 8 PICS has to be updated as per Test Plan.
- High level PICS has to be updated as per Test Plan.

### Steps to reproduce:
- TC-DISHM-3.1 - All Steps
- TC-DISHM-3.3 - Step 8

###   Yaml References:

 -  https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DISHM_3_1.yaml
 -  https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DISHM_3_3.yaml
    
###  Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_dishwasher.adoc

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32116
