### ISSUE TITLE
[TC-CNET-4.4] Step 2c has to be added in YAML script as per test plan changes

### ISSUE THREAD

**Issue by Survensa** [project-chip/matter-test-scripts#134]
## Description:
In TC-CNET-4.4, Step 2c has been added newly in test plan. So script has to be updated for the same.

**Test Plan Reference:** 

![image](https://github.com/project-chip/matter-test-scripts/assets/95559513/cba9be1d-f276-49bf-87dd-ed9e38d1cdbc)

**Comment by cecille** [comment]
Note that this test is slated to be properly automated in python. Suggesting adding the fix there instead of in the script.

**Comment by Survensa** [comment]
Python script available: https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_CNET_4_4.py
