### ISSUE TITLE
TC-DGGEN-3.1 incorrect verdict Matter 1.3 TE#2

### ISSUE THREAD

**Issue by SamCullen-Element** [project-chip/matter-test-scripts#137]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

## Summary Title: 
Matter 1.3 TE#2

## Description:
PICS printout from submitter shows DGGEN.S.A0003=0 however the attribute is present in the attributes list suggesting it is supported. Return from the test case shows it as PASSED.

## Logs:
Not Applicable, submitted in TE#2

**Comment by cecille** [comment]
Test cases assume the PICS are correct. This device should fail the pics checker test, whose job it is to verify the correctness of the PICS in this regard.

**Comment by raul-marquez-csa** [comment]
@SamCullen-Element, can you please verify if the problem persists?

**Comment by raul-marquez-csa** [comment]
Thanks @SamCullen-Element, closing issue.
