### ISSUE TITLE
[TC-APPLAUNCHER-] Manual Yaml Script has to be updated as per Verification Step document

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#139]
**Description:**
Manual Yaml Script has to be updated as per Verification Step document for below mentioned test cases 
- [x] TC-APPLAUNCHER-3.7.1 -  command has to be updated as per Verification Step document for all steps.
- [x] TC-APPLAUNCHER-3.8.1 -  command has to be updated as per Verification Step document for all steps.
- [x] TC-APPLAUNCHER-3.9.1 -  command has to be updated as per Verification Step document for all steps.

**Yaml-References:**
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_APPLAUNCHER_3_8_1.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_APPLAUNCHER_3_7_1.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_APPLAUNCHER_3_9_1.yaml

**Verification Step Document References:**
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?usp=sharing

**Comment by gvargas-csa** [comment]
This issue has been addressed in this branch https://github.com/project-chip/connectedhomeip/commit/17fc008fe270596886cb4d6f6a7d70013e48a972
