### ISSUE TITLE
[CNET] YAML script not matching the test plan

### ISSUE THREAD

**Issue by Survensa** [project-chip/matter-test-scripts#143]
## Description:
In test plan, STEP 3 says `TH finds the index of the Networks list entry with NetworkID field value PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID and saves it as 'Userwifi_netidx'` and the saved `Userwifi_netidx` is used in all the Remove network commands. But in YAML script, the `Userwifi_netidx` is not using anywhere in the test case excluding STEP 3.

### Affeted Test Cases:

1. TC-CNET-4.9: Step - 4 and 14
2. TC-CNET-4.10: Step - 4 and 14
3. TC-CNET-4.11: Step - 4 and 15

### Test Plan Reference:  
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/network_commissioning.adoc#tc-cnet-4-9-wi-fi-verification-for-removenetwork-command-dut-server

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32116
