### ISSUE TITLE
[TC-IDM-10.4(TC-pics-checker)] pics and python scripts need to be updated

### ISSUE THREAD

**Issue by liangpy4** [project-chip/matter-test-scripts#144]
## Summary Title: 
[TC-IDM-10.4(TC-pics-checker)] pics and python scripts need to be updated

## Description:
Got failures when I am testing TC-IDM-10.4(it names TC-pics-checker in the TH),  the log shows below errors:
1. An element found on the device, but the corresponding PICS DGGEN.S.C01.Rsp was not found in pics list.
2. The scripts always use endpoint 0 to check that if the device align with the PICS setting, while MicrowaveOvenMode, MicrowaveOvenControl, OperationalState clusters are not contained in the endpoint 0, these 3 clusters should be checked on endpoint 1.

## Steps to reproduce:
1. Before commission to DUT, make sure DUT in comission mode.
2. Choose TC-pics-checker and run test-case in TH.

## Logs:
TH_log:
[[FAILED][TC-IDM-10.4]_[zNw7rlE3]_TH_log.log](https://github.com/project-chip/matter-test-scripts/files/14177863/FAILED.TC-IDM-10.4._.zNw7rlE3._TH_log.log)
DUT_log:
[[FAILED][TC-IDM-10.4]_[zNw7rlE3]_DUT_log.log](https://github.com/project-chip/matter-test-scripts/files/14177864/FAILED.TC-IDM-10.4._.zNw7rlE3._DUT_log.log)

**Comment by doublemis1** [comment]
Issue in other PICS too:
[PjdW0NYp_TC_IDM_10_4.log](https://github.com/project-chip/matter-test-scripts/files/14179724/PjdW0NYp_TC_IDM_10_4.log)
[device_dump.json](https://github.com/project-chip/matter-test-scripts/files/14179725/device_dump.json)
[device_dump.txt](https://github.com/project-chip/matter-test-scripts/files/14179726/device_dump.txt)

**Comment by cecille** [comment]
PICS are set per endpoint. The test needs to be run against the appropriate endpoint with the matching PICS and endpoint value set. You need one PICS set to represent each endpoint on the device, and you need to use the --endpoint flag (or set it in the config) to set the test to the appropriate endpoint.

**Comment by VaishaliAvhale** [comment]
Hi @cecille TC-IDM-10.4 is pics-checker test case and some cluster present on endpoint: 0 and some are on endpoint:1 so how should I handle it in project config because in test_parameter I have added endpoint:1 but still application specific cluster getting check on endpoint 1.Please provide solution for the same!
Thank You!

**Comment by cecille** [comment]
I'm not sure I understand - it sounds like it's doing the right thing - you set ep1 in the config, set the pics to the pics files for ep1, it checks the clusters on ep1

**Comment by VaishaliAvhale** [comment]
@cecille, I have updated the comment. Please review again. What I am trying to say is that I have set endpoint 1 in `test_parameter`, but the application-specific cluster is still being checked on endpoint 0.

**Comment by liangpy4** [comment]
Thanks @cecille, it is worked after adding endpoint : 0 into the test_parameters, the TH will not check those items by using ep0.

But it still met another problem, see below:

PYTHON_TEST | 2024-02-18 03:30:11.101522 | [MatterTest] 02-18 03:30:10.087 INFO 
PYTHON_TEST | 2024-02-18 03:30:11.103021 | Problem: ProblemSeverity.ERROR
PYTHON_TEST | 2024-02-18 03:30:11.104375 |     test_name: PICS check
PYTHON_TEST | 2024-02-18 03:30:11.105637 |     location: 
PYTHON_TEST | 2024-02-18 03:30:11.106853 |         Endpoint: 0,
PYTHON_TEST | 2024-02-18 03:30:11.111760 |         Cluster:  51 (0x33) GeneralDiagnostics,
PYTHON_TEST | 2024-02-18 03:30:11.113221 |         Command:  1 (0x01)
PYTHON_TEST | 2024-02-18 03:30:11.114275 |     problem: An element found on the device, but the corresponding PICS DGGEN.S.C01.Rsp was not found in pics list
PYTHON_TEST | 2024-02-18 03:30:11.115341 |     spec_location:

This should be the PICS issue.

Attached log:
[[FAILED]TC-IDM-10.4_2024_02_18_11_28_23.log](https://github.com/project-chip/matter-test-scripts/files/14321251/FAILED.TC-IDM-10.4_2024_02_18_11_28_23.log)

**Comment by cecille** [comment]
PICS issue - fixed in test plans here: https://github.com/CHIP-Specifications/chip-test-plans/pull/3993
