### ISSUE TITLE
[CNET] Script has to be updated as per VS doc changes

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#15]
From chip-test-scripts created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-test-scripts#676  

**Description:**

- Pre-Condtions has to be updated for all the test cases
- **TC-CNET-4.3:** Step 8 Command and log has to be added
- **TC-CNET-4.5:** Step 1 to 3 command and step 3 PICS has to be updated 
- **TC-CNET-4.6:** Step 1 to 3 command has to be updated 
- **TC-CNET-4.9:** Step 4 Command has to be updated
- **TC-CNET-4.10:** Step 4 Command has to be updated
- **TC-CNET-4.15:** Step 2 and 3 Command has to be updated
- **TC-CNET-4.16:** Step 2 and 3 Command has to be updated

**Comment by raju-apple** [comment]
@KishokG fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by KishokG** [comment]
@raju-apple Since this issue was raised from your Id. I can't able to close this issue.
Issue is resolved so please close the issue.
