### ISSUE TITLE
[TC-S-] Script has to be updated for Scenes Management Cluster

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#150]
### Description:

- [ ] TC-S-1.1
 1.   `LastConfiguredBy(0X0000)` is a optional but it is listing in Mandatory List, So script has to be updated as per Test plan.
 
- [ ] TC-S-2.1
1.  High level PICS has to be updated as per Test Plan. 

- [ ] TC-S-2.2
1. Step 0a KeySetWrite command fields values has to be updated as per Test Plan.
2. Step 3d "TH reads attribute FabricSceneInfo from DUT" is verifying with only with CI PICS, there no another step for non CI PICS.
3. Step 8a 

-   Log has to be updated as per Verification Step document.
-    Test label has to be updated as per Test Plan.  In Test Plan Transition Time field value is 1,000(1s), But in script TransitionTime  field value is 60 000 000.

5. Step 8d Test label has to be updated as per Test Plan. In Test Plan extension fields is setting as   "a set of extension fields 
appropriate to AC1", But script is saying no extension field sets.
6. Steps 8d is Verifying with  only with CI PICS, there is no another step for non CI PICS
7. Step 8e has been removed from Test plan, So script has to be updated by removing this step.

- [ ] TC-S-2.3
 1. In Steps 0a, 0b KeySetWrite command fields values has to be updated as per Test Plan
 2. In Steps 2, 3, 6a, 6b log has to be updated as per Verification Step document.
 3. Steps 6e, 6c is Verifying with only with CI PICS, there is no another steps for non CI PICS.

- [ ] TC-S-2.4
1. Step 0a KeySetWrite command fields values has to be updated as per Test Plan
2. Step 6a, 6b PICS has to be updated 

- [ ] TC-S-2.5
1. Precondition step has to be updated as per Test plan. 
2. Command has to be updated as per Verification Step document for below steps
       -   Steps 0a, 0b, 6a, 10
3. Comment has to be updated as per Verification step document for all steps.
4. Log and Comment has to be updated as per  Verification step document for below steps
       -  Steps 3, 4a, 7a, 8a,  9a
5. PICS has to be updated as per Test plan for below steps
      -   Steps 4a, 4b

- [ ] TC-S-2.6
1. PICS has to be updated as per Test plan for below steps
    -  Steps 2a, 9b,  10b
2. Log and comment has to be updated for all steps as per Verification Step document.
3. Precondition Step has to be updated as per VS document.

### Yaml References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_2.yaml

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc

### Verification Step Document References:
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit#gid=1845308885&range=1:1028

**Comment by lpbeliveau-silabs** [comment]
@Ashwinigrl Do note that https://github.com/CHIP-Specifications/chip-test-plans/pull/3929 is still open on the chip test plan and addresses the TC-S-2.2 written above.

**Comment by lpbeliveau-silabs** [comment]
@Ashwinigrl
PRs are up for the fix to test scripts and for the test plan.
Do note that:
TC-S-2.2 : 1., 3., 5., 7. are addressed in the test plan
TC-S-2.3 : 1. is addressed in the test plan
TC-S-2.4 : 1., 2. (transitionTime PICS) are addressed in the test plan
TC-S-2.5 : 1. , 5. are addressed in the test plan
TC-S-2.6:  1. , is addressed in the test plan

**Comment by lpbeliveau-silabs** [comment]
PR in the SDK: https://github.com/project-chip/connectedhomeip/pull/32003

**Comment by lpbeliveau-silabs** [comment]
PR in the test plan: https://github.com/CHIP-Specifications/chip-test-plans/pull/3964

**Comment by Ashwinigrl** [comment]
Issue resolved
