### ISSUE TITLE
[TC-TMP-2.1] MaxMeasuredValue range has to be updated as per Spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#158]
### Description:

- [ ] TC-TMP-2.1    

**Step 3** : As per spec MaxMeasuredValue value range is from `MinMeasuredValue+1 to 32767`, but script is verifying range from `MinMeasuredValue to 32767`. So script has to be updated with valid range of MaxMeasuredValue .

### Steps to reproduce:
Step 3

### Spec References:
    
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/6928910b-a895-46f4-9546-11b3a3191be8)

- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/TemperatureMeasurement.adoc#4-attributes

### Yaml References:
    
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/7b12836b-1d72-4afa-a04a-988abe07b278)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_TMP_2_1.yaml

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32296
