### ISSUE TITLE
[TC-DGWIFI-1.1] EventList step has to be changed from step 7 to step 5 as per test plan changes

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#16]
From chip-test-scripts created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-test-scripts#677  

**Description:**

- **TC-DGWIFI-1.1:** Event list step has been changed from step 7 to 5. So the script has to be updated for the same.

**Test Plan Reference:**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/133193761/4dacaacf-7c45-4c55-a38c-7821d2ef49ee)

**Comment by raju-apple** [comment]
@KishokG fixed in PR [29747](https://github.com/project-chip/connectedhomeip/pull/29747) please verify and close the ticket.

**Comment by KishokG** [comment]
@raju-apple Since this issue was raised from your Id. I can't able to close this issue.
Issue is resolved so could you please close the issue.
