### ISSUE TITLE
[1.3] YAML script needs to be added for newly added TC - EEM, EPM - 1.1 test cases

### ISSUE THREAD

**Issue by Survensa** [project-chip/matter-test-scripts#161]
## Description:
Yaml script has to be added for below mentioned V1.3 test cases:

- TC-EEM-1.1
- TC-EPM-1.1

**Comment by raul-marquez-csa** [comment]
For TC-EEM-X.X, the test plan also mentions others that don't exist either:
![image](https://github.com/project-chip/matter-test-scripts/assets/130402456/cfbdba44-fa6b-4520-9ee6-301f664af261)
Are those also to be added?

Same question for TC-EPM-X.X
![image](https://github.com/project-chip/matter-test-scripts/assets/130402456/f408762a-2a17-422b-bbd1-d32d884f4d9a)

**Comment by Survensa** [comment]
We have python script for rest of the test case :

![image](https://github.com/project-chip/matter-test-scripts/assets/95559513/b6d2635e-cc25-4bf4-801c-93702c1a0a86)

![image](https://github.com/project-chip/matter-test-scripts/assets/95559513/1753da30-d3ac-46e1-81a2-9e32f8acc5ce)

**Comment by raul-marquez-csa** [comment]
Mentioned test cases have been removed from test plan, issue is obsolete.
