### ISSUE TITLE
[SU]OTA yaml script needs to be updated as per the test-plan

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/matter-test-scripts#163]
## Description:
The Software-update(OTA) cluster testcase has been updated in the test-plan hence the yaml script needs to be updated as per the test-plan:

- TC-SU-2.3
- TC-SU-2.5
- TC-SU-3.3

Newly added testcase:

- TC-SU-5.1

Removed testcase:

- TC-SU-4.2

**Test-plan Reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/softwareupdate.adoc

**Comment by Saravana-kr22** [comment]
@raul-marquez-csa  TC-SU-2.3, TC-SU-2.5, TC-SU-3.3 in these testcases the Step:6 `Perform the OTA Update on DUT using vendor specific mechanism.` has been removed from the test-plan 

Reference: https://github.com/CHIP-Specifications/chip-test-plans/pull/3965

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by raul-marquez-csa** [comment]
As per this comment
https://github.com/project-chip/connectedhomeip/pull/32625#pullrequestreview-1948937709
> This adds new manual tests. We are not supposed to add manual tests anymore. I assume fixing/modifying existing ones is still ok, however adding new manual steps should not happen.

TC-SU-5.1 or its functionality will remain pending, please open standalone issue for it.

**Comment by Saravana-kr22** [comment]
This issue is resolved in latest TH image.,
