### ISSUE TITLE
[TC-CNET-4.12] Script has to be updated as per VS changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#167]
## Description:

- TC-CNET-4.12 YAML script has to be updated as per VS changes.

## Steps that require to review: 
Whole test case steps has been modified in VS.

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32296

**Comment by KishokG** [comment]
Issue resolved
