### ISSUE TITLE
[Test_TC_PWRTL_1_1] - Script should be updated by adding test steps to read the AcceptedCommandList and GeneratedCommandList attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#168]
**Description:**
According to the Test-Plan, the current YAML script missed to validate the global mandatory attributes AcceptedCommandList and GeneratedCommandList. Therefore, the script should be updated to include test steps for reading these attributes.

**Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_PWRTL_1_1.yaml

**Test-Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/power_topology.adoc#tc-pwrtl-1-1-global-attributes-with-dut_server

**Missed Test-plan test-steps to validate in script :** 
6 and 7

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32296

**Comment by Rajashreekalmane** [comment]
Issue resolved
