### ISSUE TITLE
[1.3][TC-EEVSE-2.1] YAML script has to be updated as per spec with removing the Max range constraint

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#169]
## Description:

- Step 7 to 10: As per spec, Max range(80000) has to be removed from the script.

**Script Reference:** 

![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/b2dc47e7-ffed-43c2-acef-07020c1086f2)

**Specification Reference:** https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/EnergyEVSE.adoc#8-attributes

![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/b3a6ae59-3f51-481c-89d7-56ac421d86e8)

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32296

**Comment by KishokG** [comment]
Issue resolved
