### ISSUE TITLE
[TC-BRBINFO-2.1] Test step 19 - Log has to be updated as per VS doc changes

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#17]
From chip-test-scripts created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-test-scripts#678  

**Description:**

- Test step 19 - Log has been updated in VS doc. So the script has to be updated for the same.

**Comment by raju-apple** [comment]
@KishokG fixed in PR [29747](https://github.com/project-chip/connectedhomeip/pull/29747) please verify and close the ticket.

**Comment by KishokG** [comment]
@raju-apple Since this issue was raised from your Id. I can't able to close this issue.
Issue is resolved so could you please close the issue.
