### ISSUE TITLE
[TC-GRPKEY -2.1, 2.2] Script has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#171]
## Description:
 
- [x]   TC-GRPKEY-2.1
 -  Test steps 4, 7a, 7b, 9, 11 has been removed from Test Plan. So Script has to be updated as per Test Plan.
  
- [x]  TC-GRPKEY-2.2 
- Step 1 Test step label has to be updated as per Test Plan.

-  Step 26 has been newly added to the Test Plan. This Step has to be added in script according to the Test Plan.

### Steps to reproduce:
 TC-GRPKEY-2.2 -   Steps 4, 7a, 7b, 9, 11
 TC-GRPKEY-2.2 -   Steps 1, 26

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/group_communication.adoc#431-tc-grpkey-21-attributes-dut-server

###  Yaml References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_GRPKEY_2_1.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_GRPKEY_2_2.yaml

**Comment by raul-marquez-csa** [comment]
Addressed in PR
https://github.com/project-chip/connectedhomeip/pull/32296
