### ISSUE TITLE
[TC-G-3.2] `GRPKEY.C` High level PICS has to be added in the Script

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#173]
### Description:

- [ ] [TC-G-3.2] -  `GRPKEY.C` High level PICS has to be added in the Script

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Groups.adoc#tc-g-3-2-commands-dut-client

### Yaml Script References:
 - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_G_3_2.yaml

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
