### ISSUE TITLE
[TC-EEVSEM-1.1] In Step 3 Log has to be updated as per Verification Step Document.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#176]
### Description:

- [ ] **TC-EEVSEM-1.1**  - 
-  In Step 3 Log has to be updated as per Verification Step Document.  Feature Map value should be `0` in stead of `1`.

### YAML References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/e7a64811-799e-480e-9681-6952411c79d3)

- https://github.com/project-chip/connectedhomeip/blob/1.3-sve/src/app/tests/suites/certification/Test_TC_EEVSEM_1_1.yaml

### Verification Step Document References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/c5ade443-d30f-4285-baf2-fd76a57611f9)

https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit#gid=862152136&range=1:995

### Steps to reproduce:
Step 3

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
