### ISSUE TITLE
TC-DD-2.1 yaml script needs to be updated as per the test-plan.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/matter-test-scripts#177]
## Summary Title: 
TC-DD-2.1 test script needs to be updated as per the Test-plan

## Description:
TC-DD-2.1 test-case is updated with the Extended annonument step in **step 7b,** Yaml script is also needs to be updated asper the test-plan. 

## Additional Info:
**Test-plan reference:**  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#tc-dd-2-1-announcement-by-device-verification-dut-commissionee

**Comment by Rajashreekalmane** [comment]
YAML script has been update in latest TH

> Version: v2.11-beta3+fall2024
> Sha: 5d454ab

**Comment by Saravana-kr22** [comment]
This issue is resloved in lastest TH image
