### ISSUE TITLE
[TC-DESC-2.1] YAML Manual Script has to be updated as per VS document

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#178]
### Description:
  TC-DESC-2.1 - Step 2, 3 Comment has to be updated as per Verification Step document.

### Steps to reproduce:
Step 2, 3

### Yaml References:
    
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/0254dc1b-ef89-4315-86fb-89cd71a6b51f)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DESC_2_1.yaml

### Verification Step References:
    
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/4c379b96-0cc2-4d37-9516-afaf8c3c821c)

https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit#gid=1877055019&range=1:1009

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
