### ISSUE TITLE
[TC-FAN-1.1] Step 5(EventList) has to be added in script

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#18]
From chip-test-scripts created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-test-scripts#679  

**Description:**

- **TC-FAN-1.1:**  Step 5 has to be added in YAML script as per test plan.

**Script Snapshot:**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/133193761/ede4c2f0-98d1-42ef-bbea-e869a79e31c0)

**Test Plan Reference:**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/133193761/9422930a-e7fb-4fcb-83ea-148ce850d584)

**Comment by raju-apple** [comment]
@KishokG fixed in PR [29747](https://github.com/project-chip/connectedhomeip/pull/29747) please verify and close the ticket.

**Comment by KishokG** [comment]
@raju-apple Since this issue was raised from your Id. I can't able to close this issue.
Issue is resolved so could you please close the issue.
