### ISSUE TITLE
[TC-ALOGIN-12.1] - The automated script needs to be updated by removing the comment  mentioned before step 1

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#180]
**Description :** 
[TC-ALOGIN-12.1] - The automated script needs to be updated by removing the comment mentioned before step 1 because the mentioned issue has been resolved in the SDK.
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/54fb3c45-0b8a-49f3-bad1-582af287470a)

**YMAL Script Reference :** https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ALOGIN_12_1.yaml
   
**Resolved Issue in SDK** : https://github.com/project-chip/connectedhomeip/issues/28992

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Rajashreekalmane** [comment]
Issue resolved
