### ISSUE TITLE
[TC-CHENNEL-1.6] Auto - Script  should be updated for Featuremap, AcceptedCommandList attribute and GeneratedCommandList attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#181]
**Description :** 
 Script should be updated for 
- [ ] Feature map attribute by adding test-steps to validate the ElectronicGuide(EG) and RecordProgram(RP) features.
- [ ] AcceptedCommandList attribute and GeneratedCommandList attribute by adding the commands depending on ElectronicGuide(EG) and RecordProgram(RP) features.
that is 
1. GetProgramGuide
2. ProgramGuideResponse
3. ProgramGuideResponse
4. RecordProgram
5. CancelRecordProgram

**PFA Test-Plan Screenshot :** 
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/fd703f8c-afb9-4128-ad73-c820d2885836)

![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/3ea30e95-bce3-48f6-ab52-aca701119cff)

**Test-Plan Reference** : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-channel-1-6-global-attributes-channel-cluster-dut-as-server

**YMAL Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CHANNEL_1_6.yaml

**Comment by raul-marquez-csa** [comment]
Cluster revision should be updated to 2.

**Comment by Rajashreekalmane** [comment]
Script is up to date for cluster revision 
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/4d3f6544-7604-48a9-9a78-28fbe59097c0)

**Comment by cecille** [comment]
de-priorize this - test is being removed per https://github.com/CHIP-Specifications/chip-test-plans/pull/4104

**Comment by Rajashreekalmane** [comment]
TC-CHENNEL-1.6 Test case has been removed from test plan, hence closing this issue
