### ISSUE TITLE
TC-MEDIAPLAYBACK-1.7 Auto - Script should be updated for Featuremap, AttributeList, AcceptedCommandList attribute and GeneratedCommandList attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#182]
**Description :**
Script should be updated for

- [ ] Feature map attribute by adding test-steps to validate the AudioTracksand(AT), AudioAdvance(AA) and TextTracks(TT) features.
- [ ] AttributeList, AcceptedCommandList attribute and GeneratedCommandList attribute by adding the commands depending on AudioTracksand(AT), AudioAdvance(AA) and TextTracks(TT) features.
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/90f3e3f1-efc4-499f-952e-7c2070bef4ad)
 
**Test-plan Reference :** 
 https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mediaplayback-1-7-global-attributes-media-playback-cluster-dut-as-server

**Spec Reference :** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/MediaPlayback.adoc

**Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_MEDIAPLAYBACK_1_7.yaml

**Comment by raul-marquez-csa** [comment]
According to the spec, the test plan should also be updated, correct? I see AA is missing.

**Comment by Rajashreekalmane** [comment]
@raul-marquez-csaYeah, Here the test plan issue for the same : https://github.com/CHIP-Specifications/chip-test-plans/issues/3627

**Comment by raul-marquez-csa** [comment]
@Rajashreekalmane, references to attributes mentioned in

> AttributeList, AcceptedCommandList attribute and GeneratedCommandList attribute by adding the commands depending on AudioTracksand(AT), AudioAdvance(AA) and TextTracks(TT) features.

are in steps 3, 4, and 5 from the YAML

In step 3 AttributeList is mentioned, can you clarify what is being asked to do?
In step 4 AT, AA, and TT are missing, the ask would be to add them, correct?
In step 5 GeneratedCommandList is present, what is being asked?

In general, can you clarify what is being asked in this issue?

**Comment by Rajashreekalmane** [comment]
@raul-marquez-csa 
For step 2, Script need to be updated by adding the test step to validate MEDIAPLAYBACK.S.F02(TT) and MEDIAPLAYBACK.S.F03(AT) as per test-plan 

Step 3 - Script need to be updated by adding the test step to validate below mentioned attributes
7 - ActiveAudioTrack (MEDIAPLAYBACK.S.A0007(ActiveAudioTrack))
8 - AvailableAudioTracks (MEDIAPLAYBACK.S.A0008(AvailableAudioTracks))
9 - ActiveTextTrack (MEDIAPLAYBACK.S.A0009(ActiveTextTrack))
a - AvailableTextTracks (MEDIAPLAYBACK.S.A000a(AvailableTextTracks))

Step 4 -  Script need to be updated by adding the test step to validate below mentioned commands 
12 - ActivateAudioTrack (MEDIAPLAYBACK.S.C0c.Rsp(ActivateAudioTrack))
13 - ActivateTextTrack (MEDIAPLAYBACK.S.C0d.Rsp(ActivateTextTrack))
14 - DeactivateTextTrack (MEDIAPLAYBACK.S.C0e.Rsp(DeactivateTextTrack))

**Comment by cecille** [comment]
Suggest making this a low priority or just closing this issue - these tests are being removed for 1.4 per discussion at the MM.

**Comment by cecille** [comment]
Global attribute tests for clusters without choice conformance on elements are being removed as per discussion at the MM as they are now fully covered by a smaller set of IDM tests. These are normally referred to as the 1.1 tests, but the numbering is different for the media clusters.

**Comment by Rajashreekalmane** [comment]
TC-MEDIAPLAYBACK-1.7 Test case has been removed from test plan, hence closing this issue
