### ISSUE TITLE
[TC-WAKEONLAN-1.5] Script should be updated for AttributeList attribute by adding test step to validate the optional LinkLocalAddress attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#183]
Description :
[TC-WAKEONLAN-1.5] Script should be updated for AttributeList attribute by adding test step to validate the optional LinkLocalAddress attribute
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/605d0efd-b3f6-4b6b-b96a-3074af0899e7)

**Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_WAKEONLAN_1_5.yaml

**Test-plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-wakeonlan-1-5-global-attributes-wake-on-lan-cluster-dut-as-server

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by raul-marquez-csa** [comment]
This test is expected to be deleted unless this is something that's going to block cert for 1.3, as per a conversation with Cecille. It has been tagged as On-hold for now.

**Comment by Rajashreekalmane** [comment]
TC-WAKEONLAN-1.5 Test case has been removed from test plan, hence closing this issue
