### ISSUE TITLE
[TC-DEMM-1.1] In Step 3 Log has to be updated as per Verification Step Document

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#184]
### Description:

- [ ]    **[TC-DEMM-1.1]** 
- In Step 3 Log has to be updated as per Verification Step Document

### Steps to reproduce:
Step 3

### YAML References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/c079117e-589f-40d7-9f3e-f349b00fc936)

- https://github.com/project-chip/connectedhomeip/blob/1.3-sve/src/app/tests/suites/certification/Test_TC_DEMM_1_1.yaml
### Screen shot:
 ![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/3ab5c14c-6406-498f-942d-32b0f0a0ccf8)

### Verification Step document References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/1eac7abd-87e8-4654-9b6f-a5306a540a4c)
- https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit#gid=1991760408&range=1:996

## Additional Info:
**TH Version:** 2.10-beta3+spring2024
**Sha:** 1fd1429

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
