### ISSUE TITLE
[TC-CNET-4.22] Test case gets fail in UI by throwing an "Invalid commad" error

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#185]
## Description:
In TC-CNET-4.22, Step 1, 3 and 5 gets fail by throwing an "Invalid command" error.

![TC-CNET-4 22](https://github.com/project-chip/matter-test-scripts/assets/133193761/c008c3d5-6344-4ffb-ad7a-78f94d79b648)

## Logs:
[CNET_4-22_Semi_2024_02_23_13_54_36.log](https://github.com/project-chip/matter-test-scripts/files/14386088/CNET_4-22_Semi_2024_02_23_13_54_36.log)

[TC-CNET-4.22_Report.pdf](https://github.com/project-chip/matter-test-scripts/files/14386114/TC-CNET-4.22_Report.pdf)

## Additional Info:
In TE2, it's passed in TH image.

**Here is the Log:**
[CNET_4-16_4-22_2024_01_31_13_41_57.log](https://github.com/project-chip/matter-test-scripts/files/14386123/CNET_4-16_4-22_2024_01_31_13_41_57.log)

![CNET_4 22_old](https://github.com/project-chip/matter-test-scripts/assets/133193761/f49ad609-ef6a-4ec5-a804-1bb2cc162c0a)

**Comment by cecille** [comment]
This seems like a real failure to me. 

Unless you're an ethernet only device, that command is mandatory. It is sending the command on EP0, which is likely the correct endpoint for this cluster, and it's receiving back an invalid command response.

```
CHIPTOOL   | 2024-02-23 13:55:36.843007 | CHIP:DMG InvokeResponseMessage =
CHIPTOOL   | 2024-02-23 13:55:36.844088 | CHIP:DMG {
CHIPTOOL   | 2024-02-23 13:55:36.845007 | CHIP:DMG 	suppressResponse = false, 
CHIPTOOL   | 2024-02-23 13:55:36.845886 | CHIP:DMG 	InvokeResponseIBs =
CHIPTOOL   | 2024-02-23 13:55:36.855115 | CHIP:DMG 	[
CHIPTOOL   | 2024-02-23 13:55:36.857406 | CHIP:DMG 		InvokeResponseIB =
CHIPTOOL   | 2024-02-23 13:55:36.859073 | CHIP:DMG 		{
CHIPTOOL   | 2024-02-23 13:55:36.860057 | CHIP:DMG 			CommandStatusIB =
CHIPTOOL   | 2024-02-23 13:55:36.860975 | CHIP:DMG 			{
CHIPTOOL   | 2024-02-23 13:55:36.861893 | CHIP:DMG 				CommandPathIB =
CHIPTOOL   | 2024-02-23 13:55:36.862818 | CHIP:DMG 				{
CHIPTOOL   | 2024-02-23 13:55:36.863733 | CHIP:DMG 					EndpointId = 0x0,
CHIPTOOL   | 2024-02-23 13:55:36.864607 | CHIP:DMG 					ClusterId = 0x31,
CHIPTOOL   | 2024-02-23 13:55:36.865470 | CHIP:DMG 					CommandId = 0x0,
CHIPTOOL   | 2024-02-23 13:55:36.866325 | CHIP:DMG 				},
CHIPTOOL   | 2024-02-23 13:55:36.867257 | CHIP:DMG 				
CHIPTOOL   | 2024-02-23 13:55:36.868147 | CHIP:DMG 				StatusIB =
CHIPTOOL   | 2024-02-23 13:55:36.869014 | CHIP:DMG 				{
CHIPTOOL   | 2024-02-23 13:55:36.869869 | CHIP:DMG 					status = 0x85 (INVALID_COMMAND),
CHIPTOOL   | 2024-02-23 13:55:36.870852 | CHIP:DMG 				},
CHIPTOOL   | 2024-02-23 13:55:36.871737 | CHIP:DMG 				
CHIPTOOL   | 2024-02-23 13:55:36.872588 | CHIP:DMG 			},
CHIPTOOL   | 2024-02-23 13:55:36.873434 | CHIP:DMG 			
CHIPTOOL   | 2024-02-23 13:55:36.874293 | CHIP:DMG 		},
CHIPTOOL   | 2024-02-23 13:55:36.875210 | CHIP:DMG 		
CHIPTOOL   | 2024-02-23 13:55:36.876073 | CHIP:DMG 	],
CHIPTOOL   | 2024-02-23 13:55:36.876921 | CHIP:DMG 	
CHIPTOOL   | 2024-02-23 13:55:36.877782 | CHIP:DMG 	InteractionModelRevision = 11
CHIPTOOL   | 2024-02-23 13:55:36.878727 | CHIP:DMG },
```
Relevant spec:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/NetworkCommissioningCluster.adoc#commands

**Comment by cecille** [comment]
ok, can you confirm that the network commissioning cluster uses the correct feature map for a thread device?
`chip-tool networkcommissioning read feature-map 0x12344321 0`


or whatever your nodeid is

**Comment by cjandhyala** [comment]
Here is the output, it shows featuremap 2, which is 2nd bit of featuremap. 
![Screenshot 2024-04-09 at 12 07 51 PM](https://github.com/project-chip/matter-test-scripts/assets/68604034/8e56a42c-f199-45e5-bc1f-85216c882e25)
![Screenshot 2024-04-09 at 12 09 09 PM](https://github.com/project-chip/matter-test-scripts/assets/68604034/c6cdd74b-26a5-4eac-bfb8-1b8578eed804)


FYI During commissioning, I see its skipping scannetworks

[1712689388719] [43217:214640571] [TOO] CASE establishment successful
[1712689388719] [43217:214640571] [CTL] Successfully finished commissioning step 'SendNOC'
[1712689388719] [43217:214640571] [CTL] No NetworkScan enabled or WiFi/Thread endpoint not specified, skipping ScanNetworks
[1712689388719] [43217:214640571] [CTL] Commissioning stage next step: 'SendNOC' -> 'ThreadNetworkSetup'
[1712689388719] [43217:214640571] [CTL] Performing next commissioning step 'ThreadNetworkSetup'

**Comment by cecille** [comment]
ok, and is that command supported? can you check the accepted command parameter?

**Comment by KishokG** [comment]
It's PASSING in TH `Version: 2.10.1+spring2024`, `Sha: 432d504`.

**Here is the PASSING logs:**
[TC-CNET-4.22.pdf](https://github.com/user-attachments/files/15786966/TC-CNET-4.22.pdf)
[TC-CNET-4.22.log](https://github.com/user-attachments/files/15786970/TC-CNET-4.22.log)
