### ISSUE TITLE
[TC-CONTENTLAUNCHER-10.4] Manual Yaml Script has to be updated as per Verification Step document

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#187]
**Description:**
Manual Yaml Script has to be updated as per Verification Step document for below mentioned test cases
TC-CONTENTLAUNCHER-10.4 - command has to be updated as per Verification Step document for all steps.

**Verification Step Document References:**
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?usp=sharing

**Yaml-References:**
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CONTENTLAUNCHER_10_4.yaml

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Rajashreekalmane** [comment]
Issue resolved
