### ISSUE TITLE
[TC-S-2.5, 2.6]  `High level` PICS has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#188]
### Description:

- [ ] **TC-S-2.5, 2.6**
 - `High level` PICS has to be updated as per Test Plan. It should be `S.S` Instead of  `S.S,  S.S.F03.`

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#425-tc-s-25-remainingcapacity-functionality-with-dut_server
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/53aca78b-f0d8-415a-a3fa-422d2d955d71)

### Yaml Script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_5.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_6.yaml
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/415b6896-7fbb-409a-81ed-0154c8a94760)

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
