### ISSUE TITLE
[TC-S-2.4] Test step label has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#189]
### Description:

- [ ] **TC-S-2.4** 

**Test step 7b** - In User prompt,  Test step label has to be updated as per Test plan. It should be `DUT transitions to AC1 over 20s` Instead of `DUT transitions to AC2 over 20`.

### Steps to reproduce:
Test step 7b

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#424-tc-s-24-recall-scene-with-transition-time-functionality-with-dut_server

![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/a74029a0-94d8-4a02-854a-bfb4d744b32f)

### YAML References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_4.yaml    

![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/4ed875ed-cc07-4020-a78c-48549271e8bc)
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/bfcf23ce-8f8c-4855-acea-b5132d7305a2)

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32625

**Comment by Ashwinigrl** [comment]
Issue Fixed in PR https://github.com/project-chip/connectedhomeip/pull/32625. Hence closing it.
