### ISSUE TITLE
[TC-MOD-1.1] In Step 2 Cluster Revision value has to be updated as per VS document

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#19]
From chip-test-scripts created by [Ashwinigrl](https://github.com/Ashwinigrl): CHIP-Specifications/chip-test-scripts#680  

### Description:
   TC-MOD-1.1 :  In Step 2 Cluster Revision value has to be updated as per VS document

### Steps to reproduce:
Step 2

### Script Screen Shot:
  ![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/98016634/65a98bf7-48f9-45b5-a27d-da351a2c0c04)

### VS Document Screen Shot:
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/98016634/7005f12f-1a90-4897-9bec-6514d6b8e6e4)

**Comment by Ashwinigrl** [comment]
Issue Fixed
