### ISSUE TITLE
[TC-EEM-2.1] test steps preconditions are not checked

### ISSUE THREAD

**Issue by bauerschwan** [project-chip/matter-test-scripts#193]
This test case script just executes all test steps without checking the precondition of the steps.
So some test steps get executed even tho the attributes of the test step are optional and might not be used on the DUT.

`Accuracy` is the only mandatory attribute in the EEM cluster. All other attributes have a conformance other than `M` and thus might not be available.

So all test steps should use things like `if self.pics_guard(...)` to skip test steps in case the relevant PICS are not set.

**Comment by jamesharrow** [comment]
There is a similar issue raised https://github.com/project-chip/connectedhomeip/issues/32429

**Comment by raju-apple** [comment]
@raul-marquez-csa @gvargas-csa please ensure that the PR james has put up also fixes the issue Stefan has raised

**Comment by bauerschwan** [comment]
For me it fixed by [Fixes #32429 Added PICS guard to steps in TC_EEM_2_1](http://github.com/project-chip/connectedhomeip/pull/32464)
