### ISSUE TITLE
[TC-IDM-10.3] Lock/power source cluster revision not matching testplan nor spec

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/matter-test-scripts#194]
from tc-idm-10.3 scripts, it failed tests indicating mismatch clusters revision. however ones on the DUT are correct.

failure logs:
```
[MatterTest] 02-29 22:47:04.777 INFO 
Problem: ProblemSeverity.ERROR
    test_name: IDM-10.3
    location: 
        Endpoint: 1,
        Cluster:  47 (0x2f) PowerSource,
        Attribute:65533 (0xfffd)
    problem: Revision found on cluster (2) does not match revision listed in the spec (3)
    spec_location: 


[MatterTest] 02-29 22:47:04.777 INFO 
Problem: ProblemSeverity.ERROR
    test_name: IDM-10.3
    location: 
        Endpoint: 1,
        Cluster:  257 (0x101) DoorLock,
        Attribute:65533 (0xfffd)
    problem: Revision found on cluster (7) does not match revision listed in the spec (8)
    spec_location: 
```
lock cluster: 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DoorLock.adoc#1-revision-history
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#test-procedure

power source: testplan and spec mismatch
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/device_types/PowerSource.adoc#revision-history
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/powersource.adoc

**Comment by cecille** [comment]
The data model XMLs in the current SDK are correct now - cluster revision 8 is aliro support. Please see https://github.com/project-chip/connectedhomeip/blob/master/data_model/clusters/DoorLock.xml. Power source stuff was removed later (after recirc), so I will need to regenerate the DM XMLs for those based on 0.9. Will provide and update later today.

**Comment by raul-marquez-csa** [comment]
@yinyihu-silabs, is this still an issue?
