### ISSUE TITLE
[TC-S-2.2] test steps requires unittesting

### ISSUE THREAD

**Issue by xshuqun** [project-chip/matter-test-scripts#195]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

## Summary Title: 
TC-S-2.2 requires clusterID 0xfff1fc05

## Description:
TC-S-2.2 does the following step:

```
Executing Test Step: Arithmetic operation to get the maxScenes - 1
CHIP:TOO Command: unittesting test-add-arguments 15 0 0xe59da1c6139d60c8 1
```
is it mandatory to enable unittesting in zap? If DUT disable unit testing, the test fails with

```
CommandStatusIB =
{
	CommandPathIB =
	{
		EndpointId = 0x1,
		ClusterId = 0xfff1fc05,
		CommandId = 0x4,
	},
	
	StatusIB =
	{
		status = 0xc3 (UNSUPPORTED_CLUSTER),
	},
},
```

## Steps to reproduce:
1. disable unittesting
2. Use TH to run TC-S-2.2 (Semi-Automated)

## Logs:
TH logs: [TC-S-2.2.log](https://github.com/project-chip/matter-test-scripts/files/14492716/TC-S-2.2.log)

**Comment by raju-apple** [comment]
This has been resolved by syncing up with the test plan owner and modifying the test script and instead using the VS doc steps. The new VS should have this chance soon.
