### ISSUE TITLE
When running TC-PWRTL-1.1 Global attributes with DUT as Server Step4 has example AttributeList set to include FFFA (65530)

### ISSUE THREAD

**Issue by jamesharrow** [project-chip/matter-test-scripts#199]
## Summary Title: 
    Matter 1.3 SVE - When running TC-PWRTL-1.1 Global attributes with DUT as Server

## Description:
   The example shown in the verification steps shows that the EventsList should be an attribute included in the AttributeList cluster, however it is not meant to be in 1.3.

## Steps to reproduce:
    1. Look in the VS Excel sheet for PWRTL and test case TC-PWRTL-1.1
    
![image](https://github.com/project-chip/matter-test-scripts/assets/93921463/2706ffeb-b045-4e4f-866e-16aa132b3a02)

## Logs:
    N/A

## Additional Info:
    Per slack discussion - EventsList attribute should be skipped (see step 5).

**Comment by cjandhyala** [comment]
@Survensa Could you pls update the VS and close it.

**Comment by jamesharrow** [comment]
Looks good to me - I can't see the latest spreadsheet (the last one in causeway is dated 27th Feb) but based on screenshot I'm happy this is closed.

**Comment by JZ-ZZY** [comment]
So does this mean event-list is  a UNSUPPORTED  ATTRIBUTE when I read it use command ./chip-tool read event-list 1 0?

**Comment by Survensa** [comment]
> So does this mean event-list is a UNSUPPORTED ATTRIBUTE when I read it use command ./chip-tool read event-list 1 0?

YES, the `EVENT-LIST` attribute is provisional for V1.3.

**Comment by JZ-ZZY** [comment]
Thanks so much
