### ISSUE TITLE
[TC-IDM-10.2] Errors in NetworkCommissioning and MicrowaveOvenMode

### ISSUE THREAD

**Issue by xshuqun** [project-chip/matter-test-scripts#202]
## Summary Title: 
Getting errors in NetworkCommissioning and MicrowaveOvenMode for TC-IDM-10.2

## Description:
In zap, NetworkCommissioning featuremap is set to 1 but it is still showing the following:

    NetworkCommissioning shows problem: Required feature with mask 0x01 is not present in feature map. Conformance: WI, implemented features: WI

According to the specs MicrowaveOvenMode's Commands has been removed but script still checking it.
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_MicrowaveOven.adoc

    MicrowaveOvenMode shows problem: Command 0x01 is required, but is not present on the DUT. Conformance: M, implemented features: 

## Steps to reproduce:
1) Network Commissioning indicate supports for Wi-Fi
2) DUT support MicrowaveOvenMode's

## Logs:
[TC-IDM-10.2.txt](https://github.com/project-chip/matter-test-scripts/files/14505771/TC-IDM-10.2.txt)

**Comment by xshuqun** [comment]
@cecille Could you help to take a look at this? Thank you.

**Comment by cecille** [comment]
Is this a zap issue, or an issue with the test?

**Comment by cecille** [comment]
Network commissioning was supposed to be picked over to the SDK branch, but looks like it hit the darwin flake. Please see https://github.com/project-chip/connectedhomeip/pull/32305. @raju, is there a way we can get this out to folks?

**Comment by xshuqun** [comment]
@cecille It is an issue with the test script. I had doubled confirm that the NetworkCommissioning featuremap is set correctly, but the test still fails. Same with Microwave Oven Mode, where the Commands should have been removed.

**Comment by cecille** [comment]
Microwave is a script issue. Network commissioning is an issue with the data model file

**Comment by cecille** [comment]
Microwave oven fix up here: https://github.com/project-chip/connectedhomeip/pull/32465

**Comment by raju-apple** [comment]
@xshuqun were you able to re-run this with the updated script and data model file ?

**Comment by xshuqun** [comment]
@raju-apple I tried replacing the files from this PR https://github.com/project-chip/connectedhomeip/pull/32465 and the issue for Microwave Oven is resolved. 
However, after replacing NetworkCommissioningClusters.xml from this PR https://github.com/project-chip/connectedhomeip/pull/32305 in certification-tool/backend/test_collections/matter/sdk_tests/sdk_checkout/python_testing/data_model/clusters, the issue persist.
,

**Comment by xshuqun** [comment]
@raju-apple it is working now. Apparently, i made a duplicate xml and it was parsed during the test, so it was using the old xml.
