### ISSUE TITLE
[TC-ACT-3.2] chip-bridge-app does not implement an action with id 0xA001, as required by TC-ACT-3.2

### ISSUE THREAD

**Issue by Emill** [project-chip/matter-test-scripts#203]
From https://github.com/project-chip/connectedhomeip/issues/32340

### Reproduction steps

TC-ACT-3.2 specifies in the test plan pdf file that the TH has an action with id 0xA001. As "expected outcome", verify that the received ActionID containts 0xA001.

But the bridge app does not have an action with this id. Instead it has 0x1001 (4097). The Test_TC_ACT_3_2.yaml file instructs the tester to use 4097 rather than 0xA001.

This was tested on RPi Matter 1.2 Test Harness.

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

Whatever the Matter 1.2 TH uses

### Platform

core

### Anything else?

Please fix so we have consistency about the action id to use for the test. Either change the id in the pdf spec to 4097 or modify the bridge app software, yaml file and the excel test plan verification file to use 0xA001 instead.

**Comment by raju-apple** [comment]
@Survensa any thoughts on this ?

**Comment by raju-apple** [comment]
@Survensa can you double check if the step needs to be modified in VS ?

**Comment by raju-apple** [comment]
@Emill just to confirm , was this filed during the Matter 1.3 SVE or was it while using the Matter 1.2 official released TH ?

**Comment by Emill** [comment]
@raju-apple official Matter 1.2 TH.

You can see the id in the latest code here: https://github.com/project-chip/connectedhomeip/blob/master/examples/bridge-app/linux/main.cpp#L178 and the latest test plan here: https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/actions.adoc#test-procedure-3.

**Comment by raul-marquez-csa** [comment]
Issue has been resolved

**Comment by Emill** [comment]
@raul-marquez-csa I think someone was thinking too fast here... Both the yaml file and adoc file seem to have flipped the id.

Previously:
Bridge-app: 0x1001
Yaml: 0x1001
Adoc: 0xA001

Now:
Bridge-app: 0x1001
Yaml: 0xA001
Adoc: 0x1001

So, please flip yaml back since the adoc and hence the spec has been updated to reflect the value in the bridge-app.
