### ISSUE TITLE
Any Python script with a wildcard read on a device using a proprietary cluster fails. 

### ISSUE THREAD

**Issue by CoekaertsJasper** [project-chip/matter-test-scripts#205]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

## Summary Title: 
   [SVE Matter 1.3] Any IDM or Access Control Python script with a wildcard read on a device using a proprietary cluster fails. 

## Description:
    When a proprietary cluster is included in a wildcard read, the Python script fails to correctly parse the cluster and breaks. 
This occurs on IDM-10.1,  IDM-10.2,  IDM-10.3,  IDM-10.4, ACE-2.1, ACE-2.2

## Steps to reproduce:
    Please provide detailed "steps to reproduce" whenever applicable.

## Logs:
    
[TC-IDM_10-1_aLZTXeeb_Python_Docker.log](https://github.com/project-chip/matter-test-scripts/files/14515868/TC-IDM_10-1_aLZTXeeb_Python_Docker.log)

## Additional Info:
    Please include any other additional or relevant information here. Example: Spec version, PICS version, Test plan version, PICS XML files used for testing PICS, Configuration of the project, related issues,  etc.

**Comment by cecille** [comment]
Can you provide the logs from the other tests? We do know that other folks have passed these tests with MEI clusters. 

Does your cluster include write-only attributes?
This PR: https://github.com/project-chip/connectedhomeip/pull/32293 fixed the 10.1 failure for write only MEI attributes. I'm not sure when the TH was cut relative to that cherry-pick though. You may need to pull that PR and re-build the python.

**Comment by CoekaertsJasper** [comment]
Here are all the relevent logs

[TC-ACE_2_1_aLZTXeeb_Python_Docker.txt](https://github.com/project-chip/matter-test-scripts/files/14516832/TC-ACE_2_1_aLZTXeeb_Python_Docker.txt)
[TC-ACE_2_2_aLZTXeeb_Python_Docker.txt](https://github.com/project-chip/matter-test-scripts/files/14516833/TC-ACE_2_2_aLZTXeeb_Python_Docker.txt)
[TC-IDM_10_2_aLZTXeeb_Python_Docker.log](https://github.com/project-chip/matter-test-scripts/files/14516834/TC-IDM_10_2_aLZTXeeb_Python_Docker.log)
[TC-IDM_10_3_aLZTXeeb_Python_Docker.txt](https://github.com/project-chip/matter-test-scripts/files/14516835/TC-IDM_10_3_aLZTXeeb_Python_Docker.txt)
[TC-IDM_10_4_aLZTXeeb_Python_Docker.txt](https://github.com/project-chip/matter-test-scripts/files/14516836/TC-IDM_10_4_aLZTXeeb_Python_Docker.txt)
[TC-IDM_10-1_aLZTXeeb_Python_Docker.log](https://github.com/project-chip/matter-test-scripts/files/14516837/TC-IDM_10-1_aLZTXeeb_Python_Docker.log)

**Comment by cecille** [comment]
Are you running these tests from the docker directly? The errors showing there indicate that the data model files cannot be found.  Please see discussion here for how to run these tests in the docker. https://csamembers.slack.com/archives/C06JDQWTU6N/p1709110682089119 The TH should run these correctly.

**Comment by CoekaertsJasper** [comment]
I'm running all of these on the docker due to the following issue: https://github.com/project-chip/certification-tool/issues/196 . The issue seems to be fixed for the ACE TC but it fails in the same way for IDM-10.1.
[IDM_10-1_Issue.txt](https://github.com/project-chip/matter-test-scripts/files/14527610/IDM_10-1_Issue.txt)

**Comment by raju-apple** [comment]
@CoekaertsJasper the https://github.com/project-chip/certification-tool/issues/196 is fixed now , can you try the IDM_10_1 and see if it works for you now ? cc @rquidute

**Comment by cecille** [comment]
IDM 10.1 error fix: https://github.com/project-chip/connectedhomeip/pull/32293

**Comment by raul-marquez-csa** [comment]
@CoekaertsJasper, the two PRs mentioned in the comments above address most of the TCs mentioned in the description, can you verify if the issues persist?
