### ISSUE TITLE
[TC-OVENOPSTATE-2.3] script does not prompt for manual action

### ISSUE THREAD

**Issue by xshuqun** [project-chip/matter-test-scripts#206]
## Summary Title: 
TC-OVENOPSTATE-2.3 script does not stop and prompts user to perform manual action

## Description:
Script Test Steps:

    Test Step 2 : Manually put the DUT into a state wherein it can receive a Pause Command
    Test Step 3 : TH reads from the DUT the OperationalStateList attribute
However, Test Step 2 does not prompt user to perform the manual action and eventually Step 3 fails with

    mobly.signals.TestFailure: Details=3 != <ErrorStateEnum.kNoError: 0> Command response (OvenCavityOperationalState.Structs.ErrorStateStruct(errorStateID=3, errorStateLabel=None, errorStateDetails=None)) mismatched from expectation for OvenCavityOperationalState.Commands.Pause() on 1, Extras=None

## Steps to reproduce:
Run TC-OVENOPSTATE-2.3 in docker

## Logs:
[TC-OVENOPSTATE-2.3.txt](https://github.com/project-chip/matter-test-scripts/files/14518346/TC-OVENOPSTATE-2.3.txt)

**Comment by xshuqun** [comment]
Hi @cecille could you take a look at this? Appreciate your help!

**Comment by cecille** [comment]
This is a test harness issue, I believe. I don't think input is piped through to the python tests in the current version of the test harness. Carolina added support for that here: https://github.com/project-chip/connectedhomeip/pull/32299, but I'm not certain if that change appears in the current SVE test harness, and it doesn't look like that test was updated to make use of the new mechanisms.

@ccruzagralopes to confirm the current TH state. If that change is available in the current version of the TH, we can update the test to run correctly in the TH. If not, it will likely have to be run manually.

**Comment by ccruzagralopes** [comment]
I just checked the log file and the test was not run in TH, but directly in the SDK container. So I don't think this issue is related to my PR or running a test case in TH.

**Comment by cecille** [comment]
By any chance, do you have PICS_SDK_CI_ONLY set in your pics file?

**Comment by xshuqun** [comment]
@cecille After disabling PICS_SDK_CI_ONLY, it is working well now.

**Comment by cecille** [comment]
This is actually a good reminder that we should test that this pics is not set in cert. CI bypasses a number of tests that are important. Does the pics tool let you set that?
