### ISSUE TITLE
[TC-IDM-10.4] Giving error on "PICS OTAR.xxxx" was not found" which are not included in the pics list.

### ISSUE THREAD

**Issue by xilizhang1** [project-chip/matter-test-scripts#207]
## Summary Title: 
 An element found on the device, but the corresponding PICS OTAR.S.A0001 was not found in pics list.

## Logs:
[MatterTest] 03-07 05:07:50.612 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
       Endpoint: 0,
       Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor
    problem: An element found on the device, but the corresponding PICS OTAR.S was not found in pics list
    spec_location:

[MatterTest] 03-07 05:07:50.613 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
        Endpoint: 0,
        Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor,
        Attribute:0 (0x00)
    problem: An element found on the device, but the corresponding PICS [TC-IDM-10.4-fail-endpoint0.txt](https://github.com/project-chip/matter-test-scripts/files/14519200/TC-IDM-10.4-fail-endpoint0.txt)A0000 was not found in pics list
    spec_location:

[MatterTest] 03-07 05:07:50.613 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
        Endpoint: 0,
        Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor,
        Attribute:1 (0x01)
    problem: An element found on the device, but the corresponding PICS OTAR.S.A0001 was not found in pics list
    spec_location:

[MatterTest] 03-07 05:07:50.614 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
        Endpoint: 0,
        Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor,
        Attribute:2 (0x02)
    problem: An element found on the device, but the corresponding PICS OTAR.S.A0002 was not found in pics list
    spec_location:

[MatterTest] 03-07 05:07:50.614 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
        Endpoint: 0,
        Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor,
        Attribute:3 (0x03)
    problem: An element found on the device, but the corresponding PICS OTAR.S.A0003 was not found in pics list
    spec_location:

[MatterTest] 03-07 05:07:50.615 INFO
Problem: ProblemSeverity.ERROR
    test_name: PICS check
    location:
        Endpoint: 0,
        Cluster:  42 (0x2a) OtaSoftwareUpdateRequestor,
        Command:  0 (0x00)
    problem: An element found on the device, but the corresponding PICS OTAR.S.C00.Rsp was not found in pics list
    spec_location:

**Comment by akrithika27** [comment]
Or we manually add it to the pics xml

**Comment by akrithika27** [comment]
For 1.3 SVE, please ignore this specific failure. If a device fails with only this error message mark the test case as passed.

Second option is to manually add this PICS to the pics XML package and participants will select this PICS as well. For the official 1.3 release we could follow this option.

**Comment by raju-apple** [comment]
@xilizhang1  can you try to manually update the PICS XML package and try to run and see if the test passes ? For the official release we will update the PICS XML package.. cc @Survensa @cjandhyala

**Comment by xilizhang1** [comment]
we can pass the testcase after try to manually add these pics items.

**Comment by cecille** [comment]
I put up a PR to ignore these pics for now. https://github.com/project-chip/connectedhomeip/pull/32510. @raju, it's up to you how you want to fix this. I think this seems reasonable for now. We'll just have to know that the PICS files for 1.3 devices won't have OTA marked, but that's not any worse than what we have currently.
