### ISSUE TITLE
[TC-DA-1.8] - Script has to be updated as per Verification Step document 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#21]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#682  

**Description:**
[TC-DA-1.8] - Script has to be updated as per Verification Step document for step 27(as per VS)
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/3577e907-e478-4ae1-904d-ea8ab862c7f4)

**Additional Info:**
**Version**: TH Fall2023
**Sha**: 3f84bff5

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image
