### ISSUE TITLE
[Bug] [TC-DGGEN-1.1] The test script for TC-DGGEN-1.1 does not judge PICS

### ISSUE THREAD

**Issue by David-Luooo** [project-chip/matter-test-scripts#212]
### Describe the bug

The test script of TC-DGGEN-1.1 does not seem to judge PICS, and the attribute selection in the PICS of the product is inconsistent with the actual support of its firmware. The test passes without error.

### Steps to reproduce the behavior

1. In the PICS template for V_26_SVE_SPRING_2024, for General Diagnostics Cluster Test Plan.xml, Select only the mandatory attribute and select DGGEN.S.C04.Tx and DGGEN.S.C03.Rsp.
2. Start the UI-Automated test.

### Expected behavior

The test script of TC-DGGEN-1.1 is compared with the selection in PICS according to the actual situation of the product, and an error will be reported if it is inconsistent.

### Log files

[TC-DGGEN-1.1_TH.log](https://github.com/project-chip/certification-tool/files/14555423/TC-DGGEN-1.1_TH.log)

### PICS file

[General Diagnostics Cluster Test Plan.zip](https://github.com/project-chip/certification-tool/files/14555363/General.Diagnostics.Cluster.Test.Plan.zip)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/109844720/39d19690-9c7c-489a-b5e5-661c6210a116)

### Environment

TH version： 2.10-beta3+spring2024

**Comment by cecille** [comment]
PICS verification of PICS against device is done in a separate test. We have a PICS / device reporting test, and a conformance test. The 1.1 tests generally trust the PICS as provided, and they are in the process of being deprecated anyway.

**Comment by raju-apple** [comment]
@cecille but the deprecation process is going to be for 1.4 right ? We still need to have them fixed for the 1.3 release package right ?

**Comment by cecille** [comment]
There's nothing to fix - pics verification is not the purpose of this test.

**Comment by raju-apple** [comment]
Got it , i read it wrong . Thought one of the PICS was incorrectly interpreting a step .
