### ISSUE TITLE
Unit testing cluster is used in two Scenes tests

### ISSUE THREAD

**Issue by cecille** [project-chip/matter-test-scripts#216]
## Summary Title: 
The unit testing cluster is not intended for production devices. It should not be used in tests

## Description:
Unit testing appears in 
src/app/tests/suites/certification/Test_TC_S_2_2.yaml:      cluster: "Unit Testing"
src/app/tests/suites/certification/Test_TC_S_2_2.yaml:      cluster: "Unit Testing"
src/app/tests/suites/certification/Test_TC_S_2_3.yaml:      cluster: "Unit Testing"
src/app/tests/suites/certification/Test_TC_S_2_3.yaml:      cluster: "Unit Testing"

## Steps to reproduce:
grep -E 'cluster: "Unit Testing"' src/app/tests/suites/certification/*.yaml

**Comment by lpbeliveau-silabs** [comment]
Was fixed in https://github.com/project-chip/connectedhomeip/pull/35130
