### ISSUE TITLE
[TC-TCTL-3.2 AND 3.3] - Test script should be updated as per VS document 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#23]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#684  

**Description:**
[TC-TCTL-3.2] - Test script should be updated as per VS document by adding the Additional comment as "After a few seconds, please send the below mentioned command to read TemperatureSetpoint attribute from TH to DUT" for step 6, 8 and 11

[TC-TCTL-3.3] - Test script should be updated as per VS document by adding the Additional comment as "After a few seconds, please send the below mentioned command to read SelectedTemperatureLevel attribute from TH to DUT"  for step 5 and 8.

**Additional Info:**
Version: TH Fall2023
Sha: 3f84bff5

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image
