### ISSUE TITLE
Remove PICS from timesync tests

### ISSUE THREAD

**Issue by cecille** [project-chip/matter-test-scripts#230]
- [ ] TC-TIMESYNC-2.1
- [ ] TC-TIMESYNC-2.2

**Comment by j-ororke** [comment]
Latest PR for possible resolution of this issue can be found at below link: 
[PR](https://github.com/project-chip/connectedhomeip/pull/33953)

**Comment by cecille** [comment]
https://github.com/project-chip/connectedhomeip/pull/33953
