### ISSUE TITLE
[TC-DISHALM-3.x] - Test script should be updated as per VS document

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#24]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#685  

- [ ] [TC-DISHALM-3.x] Updated Reset Command at step 3a.

**PFA Script screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/feb3c80a-53c8-43e9-bf16-cf472637b4b8)
**PFA Verification Document** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/0fd05992-17c7-4b45-be6d-ee01dda59eeb)

- [ ] [TC-DISHALM-3.x]  **Pics should be updated in Script**

![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/1d525c26-44f2-459f-b2a4-922d63d4edbe)

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue has been resolved in latest Image
