### ISSUE TITLE
 [TC-DGGEN-1.1]  YAML script has to be updated for AcceptedCommandList and GeneratedCommandList attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#245]
**Description:**
The expected outcome has been updated to include the DMTEST feature depended commands . Therefore, the script should be updated to incorporate the expected outcome for the AcceptedCommandList and GeneratedCommandList attribute.

**Script Reference :**
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DGGEN_1_1.yaml
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/25cadf15-600c-4927-8d36-ebe8c35b1131)

**Test-plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-dut_server
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/3a7733f1-8bf8-493d-b0c1-759264221117)

**Comment by cecille** [comment]
Please close. Test plan is being removed.
