### ISSUE TITLE
[TC-ICDM-1.1] - Cluster Revision value need to be updated from 2 to 1 as per test-plan

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#248]
**Summary Title:** 
[TC-ICDM-1.1] - Cluster Revision value need to be updated from 2 to 1 as per test-plan.

**Test-plan Reference** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/icdmanagement.adoc#tc-icdm-1-1-global-attributes-with-dut_server
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/4f4368e3-528f-4667-a989-75b3297c78f6)

**Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_1_1.yaml

**Comment by cecille** [comment]
Please close. This test plan is being removed in 1.4
