### ISSUE TITLE
[TC-DESC-2.1] In Step 1b, 2 Script has to be updated as per VS document

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#25]
From chip-test-scripts created by [Ashwinigrl](https://github.com/Ashwinigrl): CHIP-Specifications/chip-test-scripts#686  

### Description:
TC-DESC-2.1 :- In Step 1b, 2 Script has to be updated as per VS document

### Steps to reproduce:
Step 1b, 2

### Yaml-Reference:

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DESC_2_1.yaml

### Additional Info:
Version: TH Fall2023
Sha: 3f84bff5

**Comment by raju-apple** [comment]
@Ashwinigrl fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
