### ISSUE TITLE
[TC-WNCV-5.1] - Script should be updated by removing the PICS for 1a  PICS: WNCV.C.Afffc

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#27]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#688  

**Description**  : 
[TC-WNCV-5.1] - Script should be updated by removing the PICS for 1a  (PICS: WNCV.C.Afffc) Due to the PICS ( {PICS_CA_FEATUREMAP}.Read)) at 1a, Test-step is skipping in UI .

**PFA UI Screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/547a5bc9-a8fd-48f7-8af6-5edc40c5d7bd)

**PFA Test-Plan screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/aea369f6-dc79-453f-afff-7cfb9faee385)

**PFA script screenshot :** 

![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/265c2efa-dd1c-4dea-8dcf-e4035b2c4a24)

**Additional Information** : 
Version: TH Fall2023
Sha: 3f84bff5

**Test-Plan updated :**  https://github.com/CHIP-Specifications/chip-test-plans/pull/3464

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest image
