### ISSUE TITLE
[DRLK] YAML script has to be updated as per the test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#271]
## Description:
The test plan has been updated by removing/adding some steps for below mentioned test cases. So the YAML script has to be updated for the same.

**Updated Test Case:**

- TC-DRLK-2.1 
- TC-DRLK-2.4
- TC-DRLK-2.5
- TC-DRLK-2.6
- TC-DRLK-2.7
- TC-DRLK-2.8
- TC-DRLK-2.9
- TC-DRLK-2.10
- TC-DRLK-2.11

**Here is the test plan PR's for reference:** https://github.com/CHIP-Specifications/chip-test-plans/pull/4206/ and https://github.com/CHIP-Specifications/chip-test-plans/pull/4247

**Comment by raul-marquez-csa** [comment]
@KishokG 

Can you please verify if 2 merged PRs resolve this issue?

**Comment by KishokG** [comment]
Issue fixed
