### ISSUE TITLE
[TC-S-2.2, 2.3] Script has to be updated as per Test plan changes

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#274]
### Description:
  
- [ ]  **TC-S-2.2**
 - Test steps 4e, 8f has been newly added to the Test plan, So script has to be updated as per Test plan change.
 
- [ ]  **TC-S-2.3**
- Test steps 6f, 6g, 6h, 6i has been newly added to the Test plan, So script has to be updated as per Test plan change.

### Steps to reproduce:
**TC-S-2.2** -  Test steps 4e, 8f
**TC-S-2.3**  - Test steps 6f, 6g, 6h, 6i

### Test plan PR for References:
- https://github.com/CHIP-Specifications/chip-test-plans/pull/4073

### Test plan References:
  -  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#412-tc-s-22-primary-functionality-with-dut_server

### Yaml SCript References:
  - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_2.yaml
  - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_3.yaml

**Comment by lpbeliveau-silabs** [comment]
Since these steps got added in https://github.com/project-chip/connectedhomeip/pull/32632, I think this can be closed.

@Ashwinigrl ?

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/32632. Hence closing it.
