### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-GRPKEY- 2.2 -Step22 fail

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/matter-test-scripts#275]
### Reproduction steps

Use TH Version: TH Fall2023 Sha: 27090a17 to test
Step 22 fail.
If we send the cmd manually.
`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 3,"groupKeySecurityPolicy": 0, "epochKey0":"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 1,"epochKey1":"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 18446744073709551613,"epochKey2":"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 18446744073709551614 }' 1 0` in Step 22, it actually return RESOURCE_EXHAUSTED as expected.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

181b0cb14ff007ec912f2ba6627e05dfb066c008

### Platform

other

### Platform Version(s)

ASR

### Type

Common Cluster Logic

### Anything else?

TH Log:
[TC-GRPKEY-2-2_2024_06_27_11_24_04.log](https://github.com/user-attachments/files/16009215/TC-GRPKEY-2-2_2024_06_27_11_24_04.log)

**Comment by mideayanghui** [comment]
In the step 21( manual step), I input 3 cmd as below,
`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 1,"groupKeySecurityPolicy": 0, "epochKey0":"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 1,"epochKey1":"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 18446744073709551613,"epochKey2":"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 18446744073709551614 }' 1 0`
`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 2,"groupKeySecurityPolicy": 0, "epochKey0":"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 1,"epochKey1":"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 18446744073709551613,"epochKey2":"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 18446744073709551614 }' 1 0`
`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 3,"groupKeySecurityPolicy": 0, "epochKey0":"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 1,"epochKey1":"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 18446744073709551613,"epochKey2":"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 18446744073709551614 }' 1 0`
and the cmd 3 has the output  `General error: 0x89 (RESOURCE_EXHAUSTED)`

here's the TH log  I retest but the TH reports step 23 fail.
[TC-GRPKEY-2-2_2024_06_28_09_13_01.log](https://github.com/user-attachments/files/16022942/TC-GRPKEY-2-2_2024_06_28_09_13_01.log)

**Comment by Ashwinigrl** [comment]
@mideayanghui 

Tried to reprodue the issue using the all-clusters-app (sample app) seems the execution ends without any issues 

Attached is the screenshot and output log of the TC-GRPKEY-2.2 execution.

**Snapshot :**

![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/e4cc82e1-3e71-4edf-a9bf-5f46934d8efa)

**Execution Log :**

[TC-GRPKEY-2.2.log](https://github.com/user-attachments/files/16026266/UI_Test_Run_2024_06_28_13_06_13.log)

@cjandhyala FYI

Can you please re-verify and close this issue

**Comment by mideayanghui** [comment]
@cjandhyala Hey, why you the log you provide without "---- Start of Manual Log ---",  have you been ask to use chip-tool to send cmd in step 21?

**Comment by Ashwinigrl** [comment]
@mideayanghui  We used `th-chip-tool` docker to run the manual commands that prompts in middle of the execution.

Attached the log of command that where executed manually : [TC-GRPKEY-2.2(User prompt log).txt](https://github.com/user-attachments/files/16027955/TC-GRPKEY-2.2.User.prompt.log.txt)

**Comment by mideayanghui** [comment]
Thanks, it works.
