### ISSUE TITLE
[TC-S-2.6] Manual Yaml Script has to be updated as per Test plan and  Verification step document.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#277]
### Description:

- [ ] **TC-S-2.6**

1. Step 7, 8 - Test step label, Command and Log has to be updated as per VS document and Test plan.
2. Step 11a, 11b - Command and log has to be updated as per VS document.
3. Step 1b, 1c - Comment has to be updated as per VS Document
4. Step 2d - Test step label has to be updated as per Test plan.
5. Step 3b, 4a - PICS has to be updated as per Test plan.

### Steps to reproduce:
Test steps 1b, 1c, 2d, 3b, 4a, 7, 8, 11a, 11b

### Verification Step Document References:
- https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?gid=1845308885#gid=1845308885&range=161:161

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#416-tc-s-26-remainingcapacity-functionality-with-dut_server---multi-fabric

### Yaml Script References:
   - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_6.yaml

**Comment by lpbeliveau-silabs** [comment]
Addressed everything in: https://github.com/project-chip/connectedhomeip/pull/36145,

@Ashwinigrl , I don't see the update needed for the step:
> 5. Step 3b, 4a - PICS has to be updated as per Test plan.

In the scripts, 3b has no PICS and 4a has S.S.C00.Rsp. This corresponds to the current PICS in the Test plan and VS doc no?

**Comment by Ashwinigrl** [comment]
@lpbeliveau-silabs It's my bad, steps 3b and 4a have the correct PICS as outlined in the Test Plan. There is no need of PICS update in Scripts.
