### ISSUE TITLE
[TC-ALOGIN-12.2] - Precondition should be updated as per Verification Document 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#28]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#689  

**Description** 
[TC-ALOGIN-12.1] - Precondition should be updated as per Verification Document.

**PFA UI screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/8c2fd00c-9336-4bd8-bc62-1a36888a5c84)

**PFA VS screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/5b09100a-12e7-4ae0-b05e-03b69538c6f0)

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image
