### ISSUE TITLE
Remove Test Case [TC-OPCREDS-3.2] from YAML Scripts

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#281]
**Description:**
The test case [TC-OPCREDS-3.2] already has a Python script available to validate it. Therefore, the YAML script for this test case should be removed.

**References:**

**Python Script:** https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_OPCREDS_3_2.py

**YAML Script:** https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OPCREDS_3_2.yaml

Please find the relevant Python and YAML script references above.

**Comment by raul-marquez-csa** [comment]
PR
[TC-OPCREDS-3.2 - Removes yaml script #36212
](https://github.com/project-chip/connectedhomeip/pull/36212)
