### ISSUE TITLE
TC-OPCREDS-3.3 - Manual YAML script needs to be updated according to the verification step document

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#283]
**Description:**
TC-OPCREDS-3.3: Logs have been updated for all test steps. Therefore, the manual YAML script needs to be updated according to the verification step document

**Updated Required :** 
Full test case

**Verification Step Document References:**
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?usp=sharing

**Yaml Script References:**
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OPCREDS_3_3.yaml

**Comment by Rajashreekalmane** [comment]
https://github.com/project-chip/matter-test-scripts/issues/356

**Comment by raul-marquez-csa** [comment]
PR
[TC-OPCREDS-3.3 - Updates verification steps, removes pre-condition #36211
](https://github.com/project-chip/connectedhomeip/pull/36211)
