### ISSUE TITLE
[TC-DA-1.4] Script should be updated as per verification Document 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#29]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#690  

**Description :** 
Test Script should be updated as per verification steps.

**PFA UI screenshot :** 

![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/35046437-192e-4f50-92d9-961aad74600f)

**PFA VS screenshot :** 

![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/5534dbdd-314b-43f6-b953-48cbea0aa8a1)

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image
