### ISSUE TITLE
[TC-LVL-8.1] - This test case has been newly added to the Test Plan, and it needs to be included in the YAML

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#290]
**Description:**
The test case [TC-LVL-8.1] has been newly added to the Test Plan. This test case needs to be included in the YAML script.

**Test-Plan Reference :** 
Test-Plan PR which added TC-LVL-8.1 test case  : https://github.com/CHIP-Specifications/chip-test-plans/pull/4250
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/levelcontrol.adoc#tc-lvl-8-1-verification-of-commands-dut-as-client

**Script Reference** 
![image](https://github.com/user-attachments/assets/0acde53e-b486-4646-9741-5dcfef148af6)
[src/app/tests/suites/certification
](https://github.com/project-chip/connectedhomeip/tree/master/src/app/tests/suites/certification)

**Verification Document Reference :** 
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?usp=sharing

**Comment by cjandhyala** [comment]
closer per https://github.com/project-chip/connectedhomeip/pull/35253

**Comment by naveenkommareddi** [comment]
Closed per the merged PR
