### ISSUE TITLE
[TC-S-2.5, 2.6] Yaml script has to be updated as per Test plan and VS document.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#296]
### Description:

- [ ] **TC-S-2.5**

 - In script Precondition step has to be updated as per test plan.
- In test step 4b, 5b Log has to be updated as per VS document.

### Test plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#test-setup-3

![image](https://github.com/user-attachments/assets/c4638968-47b0-4d80-b416-c59027e93ef1)

### YAML script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_5.yaml

![image](https://github.com/user-attachments/assets/c7f955a9-a964-45e6-913c-8b16d41bf64a)

### Verification step document:
- https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?gid=1845308885#gid=1845308885&range=139:139

- [ ] **TC-S-2.6**

 - In Precondition has to be updated as per Test plan.

### Test plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#test-setup-4

![image](https://github.com/user-attachments/assets/73cdf9d2-4b42-42f6-909e-4ced4788c7e4)

### YAML script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_6.yaml

![image](https://github.com/user-attachments/assets/b2576630-aff0-41a2-982c-40abbb1bc4a1)

**Comment by raul-marquez-csa** [comment]
Addressed in PR:
https://github.com/project-chip/connectedhomeip/pull/35054
