### ISSUE TITLE
[TC-S-2.2, 2.3, 2.4] YAML script has to be updated as per Test plan VS document.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#297]
### Test case IDs:
**TC-S-2.2
TC-S- 2.3
TC-S- 2.4**

### Description:

- [ ] **TC-S-2.2**

- In Test Steps 2a, 11a (**"Is DUT configured with AC1?"**) Command and log has to be updated as per VS document.
- In Test Steps 3a, 4c, 10a, 12a (**"Is DUT configured with AC2?"**) Command and log has to be updated as per VS document.
- In Test Steps 3b, 4d **"DUT returns to AC1"** is missed to verify.
- In Step 5a **ExtensionFieldSets** parameter is missing in the ViewScene command Response.
- Test Step 8a - Command has to be updated as per VS document.
- Step 8b - Test step is Saying,  set the extension fields appropriate to AC1. But it is verifying with  empty value.
- In Test Step 14a (**"Is DUT configured with AC3?"**)  Command and log has to be updated as per VS  document.
- The cluster(Unit Testing cluster) used in the precondition step does not matches the main clusters of the test case.

- [ ] **TC-S-2.3** 

- In Test Steps 2, 6a command has to be updated as per VS document.
- In Test Steps 3, 6b log has to be updated as per VS document
- In Test Step 5a - Command and log has to be updated as per VS document.
- In Test Step 5b (**"Verify DUT returns to AC1"**) Command and log has to be updated as per VS document.
- The cluster(Unit Testing cluster) used in the precondition step does not matches the main clusters of the test case.

- [ ] **TC-S-2.4**

- In Test Step 4a (**"Is DUT configured with AC1?"**) Command and log has to be updated as per VS document.
- In Test Steps 5a, 6a, 7a ( **"Is DUT configured with AC2?"**) Command and log has to be updated as per VS document.
- In Test Steps 5b, 7b (**"Is the transition done over 20s"**) Command and log has to be updated as per VS document.
- In test Step 6b (**"Is the transition done over 5s"**) Command and log has to be updated as per VS document.

### YAML SCript References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_2.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_3.yaml
 - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_4.yaml

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc

### Verification Step Document:

- https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?gid=1845308885#gid=1845308885&range=1:1042

**Comment by lpbeliveau-silabs** [comment]
TC-S-2.2 addressed in: https://github.com/project-chip/connectedhomeip/pull/35519

**Comment by lpbeliveau-silabs** [comment]
TC-S-2.3 addressed in: https://github.com/project-chip/connectedhomeip/pull/35555

**Comment by Ashwinigrl** [comment]
@lpbeliveau-silabs  
**TC-S-2.2**  - In Test step 8a Command(`ValueUnsigned8` Field name should be `valueUnsigned16` ) has to be updated as per Verification Step document. It should be updated from        
`./chip-tool scenesmanagement add-scene 0x0001 0x01 60000000 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4001", "ValueUnsigned8": "0x01"}]}]' 1 1`

**TO**

`./chip-tool scenesmanagement add-scene 0x0001 0x01 60000000 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4000", "valueUnsigned16": "0x01"}]}]' 1 1`
