### ISSUE TITLE
[TC-LVL-9.1] - Update Required for Test_TC_LVL_9_1.yaml to Align with Test Plan(for step 0b, 2a and 2b)

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#306]
**Description:**

There are discrepancies between the Test_TC_LVL_9_1.yaml file and the test plan. The following updates are required:
Step 0b:
**Current Issue:** The test step includes GroupID 0x0002, which is not included in test plan.
**Requested Update:**  The test step includes GroupID 0x0002, which should be removed 
![image](https://github.com/user-attachments/assets/e809d3bb-ee0a-464b-bf5b-6ba4a0095ced)
![image](https://github.com/user-attachments/assets/2e494076-0a4f-4152-8071-8f85975e5e61)

Steps 2a and 2b:
**Current Issue:** Steps 2a and 2b are in the incorrect order.
**Requested Update:** Interchange steps 2a and 2b to match the sequence specified in the test plan.

**Test Plan reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/levelcontrol.adoc#tc-lvl-9-1-scenes-management-cluster-interaction-with-dut_server

**YAML script reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_LVL_9_1.yaml

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/35253. Hence Closing it.
