### ISSUE TITLE
[TC-IDM-6.2] SCript should be updated as per verification Document from step 13 to18

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#31]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#692  

**Description :** 

1. Notes/Testing Considerations Need to be updated.
2. Script Should be updated as Per Verification step Document.
**PFA Script screenshot**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/7ad64281-7f7b-4eac-8e20-89a7845e47a4)

**PFA Verification Steps Doc  screenshot:** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/61ae343f-7741-4a1b-8b00-fe0c6adc7397)

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue has been resolved in latest Image.
