### ISSUE TITLE
[TC-S-3.1] Manual Yaml script has to be updated as per Verification step document

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#313]
### Description:
   **TC-S-3.1**

- [ ] **Step 1**
 - Command has to be updated as per Verification Step document.
It has to updated from  ` ./chip-tool scenesmanagement add-scene 0x0001 0x01 20 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4001", "attributeValue": "0x01"}]}]' 1 1` **to**  `./chip-tool scenesmanagement add-scene 0x0001 0x01 20 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4000", "valueUnsigned16": "0x01"}]}]' 1 1`

### Steps to reproduce:
Step 1

### Verification step document References:
 - https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?gid=1845308885#gid=1845308885&range=199:199

![image](https://github.com/user-attachments/assets/4caf8245-33bc-434e-b7a6-201e3fcb038f)

### Yaml Rferences:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_3_1.yaml

![image](https://github.com/user-attachments/assets/c159aa31-58dd-4ba1-b15d-746713129d29)

**Comment by raul-marquez-csa** [comment]
Addressed in PR:
https://github.com/project-chip/connectedhomeip/pull/35050

**Comment by Ashwinigrl** [comment]
Issue fixed in PR https://github.com/project-chip/connectedhomeip/pull/35050. Hence closing it.
