### ISSUE TITLE
[TC-CC-7.3] The test step number needs to be updated as per test plan

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#317]
## Description:
 [TC-CC-7.3] The test step number needs to be updated as per test plan after step 5c
![image](https://github.com/user-attachments/assets/e7ec3097-cda0-481c-9bc9-fdf68a5b29ed)

**Test Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/colorcontrol.adoc

**Script reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CC_7_3.yaml

**Comment by cjandhyala** [comment]
fixed in the PR https://github.com/project-chip/connectedhomeip/pull/35093
