### ISSUE TITLE
[TC-OPSTATE-2.2] Step 16 and 17 -   The PICS should be updated in the script based on VS

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#32]
From chip-test-scripts created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-test-scripts#693  

**Description :**  
[TC-OPSTATE-2.2] Step 16 and 17 -  PICS should be updated in script has per VS 

**PFA Script screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/6da9d375-bece-486b-973f-177cfe6ebe6a)

**PFA VS screenshot :** 
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/95841834/be8a4120-970d-4f33-a838-9bd677b238ef)

**Test-Plan PR that updated PICS in these steps** : https://github.com/CHIP-Specifications/chip-test-plans/commit/a0d33b87c34cc7851cb7254ffef12f280fe27bc5

**Comment by raju-apple** [comment]
@Rajashreekalmane fixed in PR [29727](https://github.com/project-chip/connectedhomeip/pull/29727) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image.
