### ISSUE TITLE
[TC-ICDM-xx] YAML script should be updated/added as per latest Test plan and Verification document

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#321]
**Description**
[TC-ICDM-xx] below mentioned YAML script should be updated as per latest Test plan and Verification document for complete test case

- [x] TC-ICDM-3.2
- [x] TC-ICDM-4.1
- [x] TC-ICDM-5.1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_1_1.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_3_2.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_3_4.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_4_1.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ICDM_5_1.yaml

 **For below mentioned test cases are need to be added** 
- [ ] TC-ICDM-5.2
- [ ] TC-ICDM-6.1

**Test Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/icdmanagement.adoc

**Comment by raul-marquez-csa** [comment]
@Rajashreekalmane 

**TC-ICDM-3.2** has been automated

**TC-ICDM-4.1** and **TC-ICDM-5.1** updates don't apply anymore as per this comment
https://github.com/project-chip/connectedhomeip/pull/35311#issuecomment-2333163267
> automated tests have coverred 4.1 and 5.1, you can remove them from this PR

**TC-ICDM-5.2** and **TC-ICDM-6.1** are new manual tests which are not being accepted in the SDK as per this comment
https://github.com/project-chip/connectedhomeip/pull/35311#discussion_r1747104161
> This is a new file containing manual tests. This will not be accepted in the SDK.

Closing this issue.

Please open new issue for **TC-ICDM-5.2** and **TC-ICDM-6.1** when an agreement is reached on how to best add them.
