### ISSUE TITLE
[TC-DEM-2.1] Yaml script needs to be added for Device Energy Management Cluster test case

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#325]
## Description:

**For below mentioned test cases, Yaml script needs to be added:**

- TC-DEM-2.1

**Comment by Ashwinigrl** [comment]
Addressed in https://github.com/project-chip/connectedhomeip/pull/34969/

**Comment by jamesharrow** [comment]
I think this is a duplicate of https://github.com/CHIP-Specifications/chip-test-plans/issues/4483 - so this could be closed?

**Comment by KishokG** [comment]
Issue fixed
