### ISSUE TITLE
Fabric sync tests `ECOINFO` and `CCTRL` need larger timeout for interactive/user input operations

### ISSUE THREAD

**Issue by andy31415** [project-chip/matter-test-scripts#329]
## Summary

Feedback from `[TE2]` on `12 Aug 2024`:

Fabric sync requires interaction with 3rd party devices and commissioning and such steps (like pair/unpair) may take significantly longer. We require defaults for user input for them to be significantly longer (say 10 minutes)
 
## Description:
   
We easily get timeout on user input when trying to execute pair/unpair operations during fabric sync. Interaction with such devices require more complex flows than simple "push button/run command" and sufficient time should be given to the operator to execute the,

**Comment by cecille** [comment]
This can be overridden on the command line with the --timeout parameter. The default can also be changed if you would like, but I don't think that's probably a blocker for SVE.

**Comment by naveenkommareddi** [comment]
based on Cecille's comments, is this still a blocker?
