### ISSUE TITLE
TC-CADMIN-1.5 yaml script Step 15 used wrong node ID

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/matter-test-scripts#33]
## Description:
Prompt from Step 15 uses node ID 1 which is used for TH_CR1 in previous steps.  
```
    - label: "Step 15: TH_CR3 starts a commissioning process with DUT_CE"
      PICS: CADMIN.S
      verification: |
          On TH_CR3 send the below command

          Below is the example when using chip tool as controller (considering 36177160937 as the manual code generated by 1st controller)
          ./chip-tool pairing code 1 36177160937 --commissioner-name gamma

          verify you got the following message in the TH_CR3(chip-tool) log
          CHIP:SC: PASESession timed out while waiting for a response from the peer. Expected message type was 33
          CHIP:TOO: Secure Pairing Failed
          CHIP:TOO: Pairing Failure: ../../third_party/connectedhomeip/src/protocols/secure_channel/PASESession.cpp:324: CHIP Error 0x00000032: Timeout
      disabled: true
```
command should use nodeID other than 1 (TH_CR1) and 2 (TH_CR2).
eg. `./chip-tool pairing code 3 36177160937 --commissioner-name gamma`

**Comment by Saravana-kr22** [comment]
@yinyihu-silabs  This is an example command and as per my understanding while using --commissioner-name gamma it becomes a separate fabric . Hence the node-id can be anything so it not mandatory to have the  different nodeId  for each instants

**Comment by yinyihu-silabs** [comment]
@Saravana-kr22 the node id has already been used by TH_CR1 in steps prior to this.  in other prompts, node id 1 is used by CR1 and id 2 is used by CR2.

**Comment by Saravana-kr22** [comment]
![image](https://github.com/project-chip/matter-test-scripts/assets/104007654/5c5ccd23-8663-432c-b9e6-a49505608470)

@manjunath-grl Verfication sheet has been updated, Please update the script.

**Comment by raju-apple** [comment]
@manjunath-grl please fix the script

**Comment by manjunath-grl** [comment]
@yinyihu-silabs fixed in PR https://github.com/project-chip/connectedhomeip/pull/30120 please verify it and close the ticket.
CC @raju-apple
