### ISSUE TITLE
[TC-SC-4.5, 4.10] Test cases are removed from test plan, Yaml script has to be updated by removing these test cases.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#333]
### Description:
   **TC-SC-4.5**, **TC-SC-4.10**  Test cases are removed from test plan, So Yaml script has to be updated by removing these test cases.

### Test plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#discovery

![image](https://github.com/user-attachments/assets/e2fa1184-474a-44ff-8e85-f83db3136cbb)

### YAML Script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SC_4_5.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SC_4_10.yaml    

### Additional Info:
**Version:** v2.11-beta2+fall2024
**Sha:** bbeda31

**Comment by cjandhyala** [comment]
fixed in PR https://github.com/project-chip/connectedhomeip/pull/35093
