### ISSUE TITLE
[TC-SWTCH-2.3][TC-SWTCH-2.5][TC-SWTCH-2.6] Errors and confusions in test prompts

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/matter-test-scripts#338]
## Summary Title: 

Several TC-SWTCH tests have incorrect and confusing prompts.

## Description:

- TC-SWTCH-2.3: 
  - BAD (does not respect step 5): `Press switch position {pressed_position} for a long time (around 5 seconds) on the DUT, then release it.`
  - GOOD: `Press switch position {pressed_position} for a long time (around 5 seconds) on the DUT, keep it pressed, do NOT release it.`

- TC-SWTCH-2.5 and TC-SWTCH-2.6:
  - CONFUSING: 'Operate the switch (press briefly) associated with position {pressed_position} then release {number_of_presses} times`.
  - BETTER: `Execute {number_of_presses} separate brief press/release cycles on position {pressed_position}.`

## Steps to reproduce:

Run affected tests

## Logs:

N/A

**Comment by cecille** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/34986
