### ISSUE TITLE
[TC-OCC-2.3] Optional attributes (XxxOccupiedToUnoccupiedThreshold)  are assumed present and tests fails on read if not

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/matter-test-scripts#339]
## Description:

in TC-OCC-2.3, there is the following code:

```
        if occupancy_sensor_type_dut == Clusters.OccupancySensing.Enums.OccupancySensorTypeEnum.kPir:
            self.step(4)
            occupancy_pir_otou_delay_dut = await self.read_occ_attribute_expect_success(endpoint=endpoint, attribute=attributes.PIROccupiedToUnoccupiedDelay)

            asserts.assert_equal(occupancy_pir_otou_delay_dut, occupancy_hold_time_dut,
                                 "HoldTime attribute value is not equal to PIROccupiedToUnoccupiedDelay")
```

This has 2 significant problems:

1- It doesn't use the featuremap, but rather uses the SensorType (which violates "2.7.6.5. Attributes to support legacy implementations") --> the featuremap should be used
2- It assumes that the attribute is present always, but it's always an optional attribute so the attribute should be considered only if present.

## Steps to reproduce:

- Run TC-OCC-2.3 against any sensor that has PIR feature or no US/PHY feature AND is missing PIROccupiedToUnoccupiedDelay attribute.

## Logs:

Log for test attached
[OCC2_2024_08_14_20_15_53.log](https://github.com/user-attachments/files/16618581/OCC2_2024_08_14_20_15_53.log)

**Comment by tcarmelveilleux** [comment]
See https://github.com/CHIP-Specifications/chip-test-plans/issues/4502

- The test script does not account for PICS
- The test script does not check for what it needs to check in the first place

**Comment by tcarmelveilleux** [comment]
There are also issues where the script is checking PIR attributes when Ultrasonic is involved:

```
        elif occupancy_sensor_type_dut == Clusters.OccupancySensing.Enums.OccupancySensorTypeEnum.kUltrasonic:
            self.step(4)
### HERE           occupancy_pir_otou_delay_dut = await self.read_occ_attribute_expect_success(endpoint=endpoint, attribute=attributes.PIROccupiedToUnoccupiedDelay)

            asserts.assert_equal(occupancy_pir_otou_delay_dut, occupancy_hold_time_dut,
                                 "HoldTime attribute value is not equal to PIROccupiedToUnoccupiedDelay")
            self.step(5)
            occupancy_us_otou_delay_dut = await self.read_occ_attribute_expect_success(endpoint=endpoint, attribute=attributes.UltrasonicOccupiedToUnoccupiedDelay)

            asserts.assert_equal(occupancy_us_otou_delay_dut, occupancy_hold_time_dut,
                                 "HoldTime attribute value is not equal to UltrasonicOccupiedToUnoccupiedDelay")
            self.skip_step(6)
```

**Comment by tcarmelveilleux** [comment]
This is also happening in TC-OCC-3.2

**Comment by jaehs6sam** [comment]
This issue is reflected in PR 35296.

**Comment by jaehs6sam** [comment]
All addressed by merged PR 35296.  Need to be closed.
