### ISSUE TITLE
Script has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#34]
### Description:
YAML script has to be updated for below test cases:

1. **TC-ACE-1.5:** Step 8 and 10 label has to be updated
2. **TC-BRBINFO-2.2:** Pre-condition step 4 has to be updated
3. **TC-DGWIFI-3.2:** Step 2 PICS has to be updated
4. **TC-CNET-4.5:** Step 2 PICS has to be updated
5. **TC-CNET-4.9:** Step 9 PICS has to be updated.
6. **TC-CNET-4.10:** Step 9 PICS has to be updated.
7. **TC-DRLK-2.10:** Step 5e Test step has to be updated(User status and User type)

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30120](https://github.com/project-chip/connectedhomeip/pull/30120) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved
