### ISSUE TITLE
TC-ICDM-2.1 Step 9 not correctly matching "UserActiveModeTriggerInstruction" to "UserActiveModeTriggerHint" [Matter1.4 TE#2]

### ISSUE THREAD

**Issue by SamCullen-Element** [project-chip/matter-test-scripts#342]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

TC-ICDM-2.1 Step 9 not correctly matching "UserActiveModeTriggerInstruction" to "UserActiveModeTriggerHint"

Step 9 validated a custom instruction text string without bit 2 of the UserActiveModeTriggerHint set to true.
The value used was 65536 (0001 0000 0000 0000 0000) and the instruction text was "\"Press the button specified in documentation\""
This led to the tool providing a PASS result for a value that does not look to match the structure of options given in the TriggerHint selected.

## Steps to reproduce:
Replicate values as set above

## Logs:
N/A - Test House as result of log review under a test event condition. Submitter will need to provide log.

## Additional Info:
    Please include any other additional or relevant information here. Example: Spec version, PICS version, Test plan version, PICS XML files used for testing PICS, Configuration of the project, related issues,  etc.

**Comment by yinyihu-silabs** [comment]
Based on the UserActiveModeTriggerHint provided, bit 16 `AppDefinedButton` is set. Instruction `Press the button specified in documentation` applies to the bit 16 hint.

If bit 2 `CustomInstruction` is set instead with the same instruction could be valid as well since it specify a custom action.

**Comment by cjandhyala** [comment]
closing the issue per comments from yinyihu and yunhan. Feel free to re-open if this issue needs to be fixed.

**Comment by SamCullen-Element** [comment]
@yinyihu-silabs @cjandhyala  just for clarification on my side then. As the summary hint for bit 16 is "Press the N Button to transition the device to ActiveMode", and hint bit 2 is Custom text and hint bit 3 is "Device Manual informs how to transition the device to Active-Mode" then How do we correctly identify that the hint is accurate to the mask?

The reason this was flagged was that the hint Bits 2 and 3 seem a lot closer to the result provided than the explination for Bit 16. If this is the case can any set bit have a reference to the documentation as suggested?

**Comment by yinyihu-silabs** [comment]
@SamCullen-Element The verification should go from UserActiveModeTriggerHint to UserActiveModeTriggerInstruction, meaning, given a Hint, if the Instruction is valid; not the other way around whether an Instruction fits another Hint better.
example: 
if bit 14 is set, Instruction 'red' is valid, but '10' is not.

in your case, if the bit 2 is set, and you get the instruction to check manual, it is valid (not ideal, but valid). it would be the same as setting bit 3, but not a failure.

@mkardous-silabs can provide more details if needed.

**Comment by SamCullen-Element** [comment]
@yinyihu-silabs That is what I was checking. The UserActiveModeTriggerBitmap only had bit 16 as true however the hint that the sample provided was "read the manual" which seemed wrong given the description of the hint in the specification but the script accepted it as a PASS.

**Comment by yinyihu-silabs** [comment]
@SamCullen-Element there is some ambiguity on bit 16.
for bit 5,6,10,11,13,15, there is an explicit statement to limit the Instruction to be digit. 
`If the [UserActiveModeTriggerHint](https://github.com/project-chip/matter-test-scripts/issues/342#ref_UserActiveModeTriggerHint) has the ActuateSensorSeconds, ActuateSensorTimes, ResetButtonSeconds, ResetButtonTimes, SetupButtonSeconds or SetupButtonTimes set, the string SHALL consist solely of an encoding of N as a decimal unsigned integer using the ASCII digits 0-9, and without leading zeros.`

**Comment by SamCullen-Element** [comment]
@yinyihu-silabs then the question is should the specification be clarified do you think if the example provided statement is permitted?
The summery statement of "press the N button to transition the device to ActiveMode" and the example given statement "please refer to the user documentation" would still not fit that case.

**Comment by yinyihu-silabs** [comment]
@mkardous-silabs Could you provide some clarity on this?

**Comment by SamCullen-Element** [comment]
@mkardous-silabs not quiet. The question here is whether the instructions in the specification are what we would expect to see.

As example; the hint selected from the spec would suggest the instruction string "press N button", with N specified by the manufacturer, but we receive "read the user manual" which does not conform to any option other than custom which has not been set as a hint.
If it is permitted to have a hint bit set, that is not custom to keep this easy, but expect any string value then what is the purpose of the table with string options to be presented when any given bit is set?

As an ATL, if you set bit x which has the string "press start 3 times" but you actually return a string of "lets have pizza" there is a question here as this is a deviation from the specification and as it looks its a defined table of acceptable options. This would get flagged and caught at testing.
