### ISSUE TITLE
[Bug] [TC-SWTCH-2.5] fails due to missing --app-pid on physical device

### ISSUE THREAD

**Issue by adamb-q** [project-chip/matter-test-scripts#346]
### Describe the bug

The test is failing with an error: `The --app-pid flag must be set when usage of button simulation named pipe is required (e.g. CI),` but the actual device is physical.

[[TC-SWTCH-2.5]_[eWg0ZwBp]_TH_log.log](https://github.com/user-attachments/files/16598175/TC-SWTCH-2.5._.eWg0ZwBp._TH_log.log)

### Environment

Version: v2.11-beta2+fall2024
Sha: bbeda31

**Comment by cecille** [comment]
Are you attempting to use the button simulator on a physical device?

Does your pics file have PICS_SDK_CI_ONLY set?

**Comment by adamb-q** [comment]
I was not passing any PICS to the test, I used the command provided in excel instructions:
 `python3 TC_SWTCH.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --paa-trust-store-path /credentials/development/paa-root-certs/ --tests test_TC_SWTCH_2_5`
I was using physical device, and skipped app_id and use_button_simulator:true params, like it was suggested on slack

**Comment by cecille** [comment]
fixed by https://github.com/project-chip/connectedhomeip/pull/34986
