### ISSUE TITLE
[Bug] TC-CNET-4.13 Step2 provided command used a wrong parameter.

### ISSUE THREAD

**Issue by slidesoon** [project-chip/matter-test-scripts#347]
### Describe the bug

Step 2: TH readsNetworksattribute from theDUT and saves thenumber of entries as 'NumNetworks'

./chip-tool network-commissioning read networks 1 0

It should be
./chip-tool networkcommissioning  read networks 1 0

**Comment by robszewczyk** [comment]
related PR was merged.
