### ISSUE TITLE
[TC-OPCREDS-3.3 ] Precondition need to be removed 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#356]
**Description:**
The current precondition for the TC-OPCREDS-3.3 test case is not necessary for the test's execution and should be removed.
![image](https://github.com/user-attachments/assets/014ba9ee-7d1b-4b19-a639-b95d8abcab06)
![image](https://github.com/user-attachments/assets/b1d13edf-34d3-49cc-a4f2-f2310ef761ca)

**Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OPCREDS_3_3.yaml

**Test Plan Reference** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/node_operational_credentials.adoc#tc-opcreds-3-3-attribute-nocs-commands-dut-client

**Comment by raul-marquez-csa** [comment]
PR
[TC-OPCREDS-3.3 - Updates verification steps, removes pre-condition #36211
](https://github.com/project-chip/connectedhomeip/pull/36211)
