### ISSUE TITLE
[TC-DEMM-1.2] In Test step 2 comment has to be updated as per Verification step document

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#364]
### Description:
**TC-DEMM-1.2** - In test step 2, the comment needs to be updated as per the Verification Step document. The test plan has been updated to correct the cluster-derived tag values defined in the expected outcome, so the script must be updated accordingly.

### Steps to reproduce:
Test step 2

### Test plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_device_energy_management.adoc

![image](https://github.com/user-attachments/assets/ca999328-53ba-4787-aaaf-c1f6fab993dc)

![image](https://github.com/user-attachments/assets/9ba04107-d210-460d-a8c6-92b2fb6afe73)

### Test plan PR for References:
- https://github.com/CHIP-Specifications/chip-test-plans/pull/4629

### Yaml Script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DEMM_1_2.yaml

![image](https://github.com/user-attachments/assets/3f2994d2-20da-425a-9a93-1f82b471f905)
![image](https://github.com/user-attachments/assets/0449a245-450f-4c49-9192-aa2b2202ae0b)

**Comment by raul-marquez-csa** [comment]
@Ashwinigrl

Current script already has step1 and step2 as per verification steps.

However, the current test plan includes two additional steps not covered in either the verification steps document or the script. Please update the document with the new steps so I can update the script accordingly.

![{AEB0BD78-FD24-4634-83E3-273335D663B3}](https://github.com/user-attachments/assets/733021ed-e3f5-450d-9db0-55b27b81eb8b)

**Comment by Ashwinigrl** [comment]
@raul-marquez-csa 

Test steps 4 and 5 should be removed from the test plan, as these are disallowed for the Device Energy Management Mode cluster. Therefore, no script updates are required.

Additionally, the above issue is in test step 2, where the comment needs to be updated according to the Verification Step document. In the script, the comments in row numbers 39 and 40 are incorrect and need correction.

**For Row no 39 :** It should be updated from **"for at least one Value field: Is the mode tag value a defined common tag value (Auto(0x0000), Quick(0x0001), Quiet(0x0002), LowNoise(0x0003), LowEnergy(0x0004), Vacation(0x0005), Min(0x0006), Max(0x0007), Night(0x0008), Day(0x0009)) or a derived cluster value (RapidCool, RapidFreeze)"**  
To 
**for at least one Value field: Is the mode tag value a defined common tag value (Auto(0x0000), Quick(0x0001), Quiet(0x0002), LowNoise(0x0003), LowEnergy(0x0004), Vacation(0x0005), Min(0x0006), Max(0x0007), Night(0x0008), Day(0x0009)) or a derived cluster value (No Optimization, Device Optimization, Local Optimization, Grid Optimization)**. 

And 

**In Row no 40 :** It should be updated from  **"Verify that at least one ModeOptionsStruct entry includes either the RapidCool semantic tag or the RapidFreeze semantic tag in the SemanticTags field"**
 To 
**" Verify that at least one SupportedModes entry includes the No Optimization mode tag or Local Optimization mode tag or Grid Optimization mode tag."**

**Comment by raul-marquez-csa** [comment]
> In the script, the comments in row numbers 39 and 40 are incorrect and need correction.

Got it.

> Test steps 4 and 5 should be removed from the test plan, as these are disallowed for the Device Energy Management Mode cluster. Therefore, no script updates are required.

Is there already a PR for that?

**Comment by Ashwinigrl** [comment]
> Is there already a PR for that?

 Test plan Issue raised for that. As of now there is no Test plan PR.

**Test plan Issue:** https://github.com/CHIP-Specifications/chip-test-plans/issues/4777

**Comment by raul-marquez-csa** [comment]
PR
[TC-DEMM-1.2 - Updates step1 #36313
](https://github.com/project-chip/connectedhomeip/pull/36313)
