### ISSUE TITLE
YAML/Python scripts needs to be removed(deleted) from the repo as the test cases were removed from the test plan

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#378]
## Description:

**Below mentioned test cases YAML/Python scripts needs to be removed from the repository as those test cases were removed from the test plan:**

- TC-PCC-1.1
- TC-WNCV-1.1
- TC-TSTAT-1.1
- TC-SWTCH-1.1
- TC-LTIME-1.2
- TC-CMOCONC-1.1
- TC-CDOCONC-1.1
- TC-NDOCONC-1.1
- TC-OZCONC-1.1
- TC-PMICONC-1.1
- TC-FLDCONC-1.1
- TC-PMHCONC-1.1
- TC-PMKCONC-1.1
- TC-TVOCCONC-1.1
- TC-RNCONC-1.1
- TC-LWM-3.1
- TC-LWM-3.2
- TC-LWM-3.3
- TC-DISHM-3.1
- TC-DISHM-3.2
- TC-DISHM-3.3
- TC-TCCM-3.1
- TC-TCCM-3.2
- TC-TCCM-3.3
- TC-SMOKECO-1.1
- TC-OTCCM-3.1
- TC-OTCCM-3.2
- TC-OTCCM-3.3
- TC-PWRTL-1.1
- TC-CNET-1.3
- TC-MWOCTRL-1.1

**Test plan removal PR for reference:**  https://github.com/CHIP-Specifications/chip-test-plans/pull/4760 & https://github.com/CHIP-Specifications/chip-test-plans/pull/4754

**Comment by Ashwinigrl** [comment]
Same for TC-MOD-1.3 has been removed from Test plan in PR [4766](https://github.com/CHIP-Specifications/chip-test-plans/pull/4766) . So YAML script has to be removed.

**Comment by raul-marquez-csa** [comment]
PR:
[Removes test case scripts #36185
](https://github.com/project-chip/connectedhomeip/pull/36185)
