### ISSUE TITLE
Test plan for validating AP-side PDC Wi-Fi authentication

### ISSUE THREAD

**Issue by ksperling-apple** [project-chip/matter-test-scripts#39]

**Comment by raju-apple** [comment]
@ksperling-apple Why are we filing Test Plan tickets in this repo ? Shouldn't we be using https://github.com/CHIP-Specifications/chip-test-plans this repo instead ?

**Comment by ksperling-apple** [comment]
Sorry I guess I got told the wrong repo. Are you able to move these issues into the correct one or do I need to recreate them?
