### ISSUE TITLE
[BUG] Failure to timeout after 20 iterations of incorrect passcode

### ISSUE THREAD

**Issue by j-ororke** [project-chip/matter-test-scripts#459]
**Pre-Requisites:**
- TH_CR1 = Test harness as Commissioner 1
- TH_CR2 = Test harness as Commissioner 2
- DUT = Commissionee

**Steps to Reproduce:**
1. Commission DUT to TH_CR1
2. TH_CR1 reads the BasicCommissioningInfo attribute from the General Commissioning cluster on EP0 and saves the MaxCumulativeFailsafeSeconds as timeout
3. TH_CR1 sends an OpenCommissioningWindow command to the DUT with the CommissioningTimeout set to timeout
4. TH_CR2 attempts to establish a PASE connection to the DUT 20 times, using a valid onboarding payload with an incorrect setupcode.
5. TH_CR2 attempts to establish a PASE to the DUT using the correct onboarding payload.

**Expected Results:**
Commissioning attempt should fail with timeout status: 
- Failed to establish secure session to device: src/controller/python/ChipDeviceController-ScriptPairingDeviceDiscoveryDelegate.h:59: CHIP Error 0x00000032: Timeout

**Actual Result:**
When running test without adding any sleep time between iteration 20 and iteration 21 we get the following unexpected error code and output:
- [MatterTest] 07-17 22:54:20.802 ERROR PASESession timed out while waiting for a response from the peer. Expected message type was 33
- Failed to commission: src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:89: CHIP Error 0x00000003: Incorrect state

**Log snippet of issue:**
```
07-18 00:02:08.137 ERROR PASESession timed out while waiting for a response from the peer. Expected message type was 33
07-18 00:02:08.138 DEBUG SecureSession[0xffffa406eb30]: Released - Type:1 LSID:39910
07-18 00:02:08.138 ERROR Secure Pairing Failed
07-18 00:02:08.139 INFO Commissioning complete done. Successful? False, errorcode = src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:89: CHIP Error 0x00000003: Incorrect state
07-18 00:02:08.141 ERROR Exception occurred in test_TC_ADMIN_1_9.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 783, in exec_one_test
    test_method()
  File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 1547, in async_runner
    return asyncio.run(runner_with_timeout)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/root/python_testing/scripts/sdk/TC_CADMIN_1_9.py", line 105, in test_TC_ADMIN_1_9
    await self.CommissionAttempt(params, expectedErrCode=0x32)
  File "/root/python_testing/scripts/sdk/TC_CADMIN_1_9.py", line 79, in CommissionAttempt
    asserts.assert_true(errcode.sdk_code == expectedErrCode, 'Unexpected error code returned from CommissioningComplete')
  File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 353, in assert_true
    fail(msg, extras)
  File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 475, in fail
    raise signals.TestFailure(msg, extras)
mobly.signals.TestFailure: Details=Unexpected error code returned from CommissioningComplete, Extras=None

```
**Notes:**
Attempted this testing in a automated manner with following python3 test script: 
- https://github.com/project-chip/connectedhomeip/pull/34342 

### Bug prevalence

Frequent

### GitHub hash of the SDK that was being used

"11f94c383171b709712106362e902f65253f4968"

### Platform

raspi

### Anything else?

Attached debug log from recent test attempt:
[test_log.DEBUG.txt](https://github.com/user-attachments/files/16276071/test_log.DEBUG.txt)

**Comment by murda-sigma** [comment]
Hello

My team is working on a project with developing Matter<->BLE Bridge device using ESP32-C6. We are now in testing phase before sending the device to the certification lab.

I just observed the same issue during our testing, we perform tests on following platform:
 - Raspberry PI 5 as Test Harness
 - TH version: v2.11+fall2024 sha: 8f86ccd
 - SDK reposotory checked out to: tags/v1.4.0.0
 - DUT: ESP32-C6 with Root & Aggregator nodes with User-Intent Commissioning flow (on BOOT button press)

The TC_CADMIN-1.9 was failing on step
 `5. Verify that the PASE connection cannot be established since the commissioning window is closed after 20 incorrect attempts.`

It was due to invalid CHIPError: TH received 0x03 instead of 0x32 at 21 attempt:
`root@ubuntu:~# python3 python_testing/scripts/sdk/TC_CADMIN_1_9.py --commissioning-method ble-wifi --wifi-ssid <WIFI> --wifi-passphrase <WIFI_PWD> --discriminator 3840 --passcode 20202021 --storage-path python_testing/admin_storage.json --paa-trust-store-path /paa_roots/`
```[MatterTest] 07-31 11:40:24.088 INFO -----------------Attempting connection expecting timeout-------------------------
[MatterTest] 07-31 11:40:24.099 INFO Avahi browse: cache new
[MatterTest] 07-31 11:40:24.100 INFO Avahi browse: cache new
[MatterTest] 07-31 11:40:24.100 INFO Avahi browse: cache exhausted
[MatterTest] 07-31 11:40:24.100 INFO Avahi browse: all for now
[MatterTest] 07-31 11:40:24.102 INFO Avahi resolve found
[MatterTest] 07-31 11:40:24.103 INFO Discovered Device: 10.42.0.192:5540
[MatterTest] 07-31 11:40:24.104 INFO <<< [E:22441i S:0 M:29242764] (U) Msg TX from 9968BFB7A0D150E2 to 0:0000000000000000 [0000] [UDP:10.42.0.192:5540] --- Type 0000:20 (SecureChannel:PBKDFParamRequest) (B:98)
[MatterTest] 07-31 11:40:24.105 INFO ??1 [E:22441i S:0 M:29242764] (U) Msg Retransmission to 0:0000000000000000 in 390ms [State:Active II:500 AI:300 AT:4000]
[MatterTest] 07-31 11:40:24.105 INFO Sent PBKDF param request [II:500ms AI:300ms AT:4000ms)
[MatterTest] 07-31 11:40:24.106 INFO Setting wifi credentials from parameters
[MatterTest] 07-31 11:40:24.106 INFO Setting attestation nonce to random value
[MatterTest] 07-31 11:40:24.106 INFO Setting CSR nonce to random value
[MatterTest] 07-31 11:40:24.106 INFO Commission called for node ID 0x0000000012344321
[MatterTest] 07-31 11:40:24.107 INFO Avahi resolve found
[MatterTest] 07-31 11:40:24.137 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.138 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.139 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.139 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.140 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.141 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.142 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.142 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.143 INFO Avahi browse: remove
[MatterTest] 07-31 11:40:24.230 INFO >>> [E:22441i S:0 M:234429183 (Ack:29242764)] (U) Msg RX from 0:0000000000000000 [0000] to 9968BFB7A0D150E2 --- Type 0000:10 (SecureChannel:StandaloneAck) (B:26)
[MatterTest] 07-31 11:40:34.563 ERROR PASESession timed out while waiting for a response from the peer. Expected message type was 33
[MatterTest] 07-31 11:40:34.564 ERROR Secure Pairing Failed
[MatterTest] 07-31 11:40:34.564 WARNING Failed to establish secure session to device: src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:96: CHIP Error 0x00000003: Incorrect state
[MatterTest] 07-31 11:40:34.564 INFO Commissioning complete done. Successful? False, errorcode = CHIP Error 0x00000003: Incorrect state

```

 I increased the sleep command in:
  https://github.com/project-chip/connectedhomeip/blame/v1.4.0.0/src/python_testing/TC_CADMIN_1_9.py#L124
from 1 to 2 seconds and the test passed:

```[MatterTest] 07-31 12:16:01.319 INFO -----------------Attempting connection expecting timeout-------------------------
[MatterTest] 07-31 12:16:01.331 INFO Avahi browse: cache exhausted
[MatterTest] 07-31 12:16:01.331 INFO Avahi browse: all for now
[MatterTest] 07-31 12:16:31.351 ERROR Mdns discovery timed out
[MatterTest] 07-31 12:16:31.351 WARNING Failed to establish secure session to device: src/controller/python/ChipDeviceController-ScriptPairingDeviceDiscoveryDelegate.h:59: CHIP Error 0x00000032: Timeout
[MatterTest] 07-31 12:16:31.352 INFO Commissioning complete done. Successful? False, errorcode = CHIP Error 0x00000032: Timeout
```
