### ISSUE TITLE
[TC-SWTCH-2.2] Script has to be updated as per Verification Step document .

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#47]
### Description:

- [ ]   [TC-SWTCH-2.2]
 - In TC-SWTCH-2.2 Manual YAML script has to be updated as per Verification step document .

### Yaml-Reference:
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SWTCH_2_2.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30120](https://github.com/project-chip/connectedhomeip/pull/30120) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue fixed
