### ISSUE TITLE
[TC-G-2.2 ] Step 1c - Script has to be updated as per Test plan changes

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#48]
### Description:
[TC-G-2.2 ] - In Step 1c Test step label  has to be updated as per Test plan change

### Steps to reproduce:
 Step 1c

### Yaml  Reference:
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_G_2_2.yaml

### Test Plan Reference:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Groups.adoc#tc-g-1-1-global-attributes-with-dut_server

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30120](https://github.com/project-chip/connectedhomeip/pull/30120) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
