### ISSUE TITLE
[CNET] Manual script has to be updated as per VS doc changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#49]
**Description:**
Script has to be updated for below mentioned test cases as per VS doc changes:
- **TC-CNET-4.5:** Step 1 Command has to be updated
- **TC-CNET-4.11:** Step 5 and 16 Command has to be updated
- **TC-CNET-4.20:** Step 3 Command has to be updated

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30120](https://github.com/project-chip/connectedhomeip/pull/30120) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved
