### ISSUE TITLE
Manual script has to be updated as per VS changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#50]
### Description:
**Script has to be updated for below changes:**
**TC-DRLK-3.2:** Command and log has been updated in VS doc. So script has to be updated for the same. 
**TC-ACT-3.2:** Step 0 and 1 Command, comment and log has to be updated.

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30120](https://github.com/project-chip/connectedhomeip/pull/30120) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved
