### ISSUE TITLE
Manual script has to be updated as per VS changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#53]
#### Description:

- **TC-ACT-2.2:** Step 4c,4d and 4e has to be updated as per VS doc.
-  **TC-ACT-3.2:** Step 2 has to be updated as per VS doc.
- **TC-DRLK-3.2:** Comment has to be updated for all the steps as per VS doc.

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved
