### ISSUE TITLE
[BOOL-2.2] Pics needs to updated in the Yaml script.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/matter-test-scripts#56]
## Description:
In TC-BOOL-2.2 Pics has been updated in the tes-plan , Hence the script needs to updated as per the test-plan.

- BOOL.M.ManuallyControlled has been updated to BOOL.S. M.ManuallyControlled

**Test-plan Reference:**https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/booleanstate.adoc

**Script Reference**https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_BOOL_2_2.yaml

**Comment by manjunath-grl** [comment]
@Saravana-kr22 fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.
