### ISSUE TITLE
[BINFO-1.1] Cluster Revision value needs to be updated.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/matter-test-scripts#58]
## Description:
In TC-BINFO-1.1 cluster Revision value has been updated from 2 to 3 , Hence the script needs to be updated as per the test-plan.

![image](https://github.com/project-chip/matter-test-scripts/assets/104007654/8f092575-c0cc-4959-a5fa-7295917ef1b4)

**Comment by manjunath-grl** [comment]
@Saravana-kr22 fixed in PR [30496](https://github.com/project-chip/connectedhomeip/pull/30496) please verify it and close the ticket.
