### ISSUE TITLE
[TC-SWTCH-2.2, 3.2] Yaml Script has to be updated as per Test plan change

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#60]
### Description:

- [ ] TC-SWTCH-2.2:- In script test step label has to be updated as per Test plan
- [ ] TC-SWTCH- 3.2 :- PICS has to be updated as per Test plan

### Test plan Reference:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/switch.adoc#tc-swtch-2-2-primary-functionality-with-server-as-dut

### Yaml Script Reference:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SWTCH_2_2.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
