### ISSUE TITLE
[TC-BIND-2.2, 2.3] High level PICS of GroupKeyManagement Cluster has to be added in Script

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#61]
### Description:
[TC-BIND-2.2, 2.3] :- In Script High level PICS `GRPKEY.C` of GroupKeyManagement Cluster has to be added.

### Test Plan Reference:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/switch.adoc

### Yaml Reference:
 -  https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_BIND_2_2.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
