### ISSUE TITLE
[TC-CADMIN-1.8] The pairing timeout message is not consistent with the expected result.

### ISSUE THREAD

**Issue by lion6420** [project-chip/matter-test-scripts#63]
## Description:
In TC-CADMIN-1.8 step7 and step12.
TH_CE: chip-all-cluster-app (TH2023 fall on raspberry-pi)
DUT_CR1: chip-tool (TH fall2023 on raspberry-pi)
TH_CR2: chip-tool (TH fall2023 on raspberry-pi)

#### The expected result in YAML:
```
CHIP:SC: PASESession timed out while waiting for a response from the peer. Expected message type was 33
CHIP:TOO: Secure Pairing Failed
CHIP:TOO: Pairing Failure: ../../third_party/connectedhomeip/src/protocols/secure_channel/PASESession.cpp:324: CHIP Error 0x00000032: Timeout
```
#### The real result I got is:
```
[1699953963.007375][2294:2294] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
[1699953963.007430][2294:2294] CHIP:DL: Inet Layer shutdown
[1699953963.007476][2294:2294] CHIP:DL: BLE shutdown
[1699953963.007523][2294:2294] CHIP:DL: System Layer shutdown
[1699953963.008313][2294:2294] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:588: CHIP Error 0x00000032: Timeout
```

**Comment by lion6420** [comment]
Hi @manjunath-grl, is it confirmed an issue and wait the test script being modified, or it need further investigation?

**Comment by Saravana-kr22** [comment]
@manjunath-grl the log wasa updated for step 7 and 12 in the VS sheet

![image](https://github.com/project-chip/matter-test-scripts/assets/104007654/8f68f079-54d0-4705-8da3-2f504601fc40)

**Comment by Saravana-kr22** [comment]
Hi @lion6420 , It is not issue both the log state that the pairing is failed due to timeout, Which is the actual result. Here in step 7 and 12 the execpted outcome is to check that the commissioning is failed. So if the  Commissioning window is closed the pairing will result in timeout error.

**Comment by lion6420** [comment]
@Saravana-kr22 Got it ! Thank you for your reply.

**Comment by manjunath-grl** [comment]
@lion6420 fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.
