### ISSUE TITLE
[TC-G-2.2, 2.3, 2.4] Test step label has to be updated as per Test plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#65]
### Description:
**Test step label has to be updated as per Test plan, for below Test cases.**

- [ ] TC-G-2.2 - Step 1a
- [ ] TC-G-2.3 -Step 1a
- [ ] TC-G-2.4 - Step 2

### Yaml References:
 https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_G_2_2.yaml

### Test plan References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Groups.adoc#422-tc-g-22-commands---addgroup-viewgroup-removegroup-removeallgroups-dut-server

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30575](https://github.com/project-chip/connectedhomeip/pull/30575) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
