### ISSUE TITLE
 Cluster Revision value needs to be updated for Media cluster test cases.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#68]
**Description:**
 cluster Revision value has been updated from 1 to 2 for below mentioned test cases, Hence the script needs to be updated as per the spec.

- [ ] TC-ALOGIN-1.12 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/AccountLogin.adoc#revision-history
- [ ]  TC-TGTNAV-1.9
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/TargetNavigator.adoc
- [ ] TC-CONTENTLAUNCHER-1.11
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/ContentLauncher.adoc#revision-history
- [ ] TC-MEDIAPLAYBACK-1.7
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/MediaPlayback.adoc#revision-history

![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/4358628c-03b0-4394-b527-cedb83b81c7f)

**Comment by Rajashreekalmane** [comment]
Test-plan issues to update the cluster revision value as per Spec
https://github.com/CHIP-Specifications/chip-test-plans/issues/3626
https://github.com/CHIP-Specifications/chip-test-plans/issues/3627
https://github.com/CHIP-Specifications/chip-test-plans/issues/3625
https://github.com/CHIP-Specifications/chip-test-plans/issues/3649

**Comment by Rajashreekalmane** [comment]
SDK issues to update the cluster revision value as per Spec
https://github.com/project-chip/connectedhomeip/issues/30411
https://github.com/project-chip/connectedhomeip/issues/30410
https://github.com/project-chip/connectedhomeip/issues/30409
https://github.com/project-chip/connectedhomeip/issues/30261

**Comment by raul-marquez-csa** [comment]
These proposed changes are already in master
https://github.com/project-chip/connectedhomeip/tree/master

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_ALOGIN_1_12.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_TGTNAV_1_9.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CONTENTLAUNCHER_1_11.yaml
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_MEDIAPLAYBACK_1_7.yaml
