### ISSUE TITLE
[TC-CC-1.1, 2.1] Script has to be updated as per Spec and Test plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#70]
### Description:
**Script has to be updated for below steps**
**TC-CC-1.1** 

- [ ] As per Spec `NumberOfPrimaries` attribute is Mandatory, But Script is verifying as Optional attribute in AttributeList.
- [ ] In Script Test Step Label for  All the feature dependent Attributes and Commands are mentioned as Optional attributes, It should be Feature Dependent Attribute and  Feature Supporting PICS are missing in the step which is Verifying the attributes which are all Feature dependence.

**TC-CC-2.1**

- [ ] In step 16 `ColorLoopTime` attribute max range has to be updated from `65534` to `65535` as per spec.

### Spec References:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ColorControl.adoc

### Test Plan References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/colorcontrol.adoc#411-tc-cc-11-global-attributes-with-server-as-dut

### Additional Info:
**Raised Test Plan PR for the same:** https://github.com/CHIP-Specifications/chip-test-plans/pull/3477
Once the PR is merged script has to be updated

**Comment by manjunath-grl** [comment]
@Ashwinigrl  we will fix the script once test-plan PR [3477](https://github.com/CHIP-Specifications/chip-test-plans/pull/3477) gets merged.

**Comment by Ashwinigrl** [comment]
Issue Fixed
