### ISSUE TITLE
[TC-SC-5.2]  Test step label has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#71]
### Description:
TC-SC-5.2 - Test step label has to be updated as per Test Plan In Steps 1, 10.

### Steps to reproduce:
Step 1, 10

### Script References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/9aabecb6-0fb4-4e71-b4bf-6bb062f62db4)
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SC_5_2.yaml

### Test Plan References::
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/77f7c013-8dbd-4d6b-8895-3bead0eb01f5)

- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/group_communication.adoc#test-procedure-4

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30869](https://github.com/project-chip/connectedhomeip/pull/30869) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed in PR https://github.com/project-chip/connectedhomeip/pull/30869
