### ISSUE TITLE
[TC-OCC-1.1] Script missed to validate the optional attributes in AttributeList.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#72]
### Description:

- [ ] TC-OCC-1.1 - In Step 4 Script missed to validate the optional attributes in AttributeList.

### Steps to reproduce:
Step 4

### Spec References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/9b143f18-2c50-458d-b04b-09d595b82344)
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OccupancySensing.adoc#5-attributes

### Yaml - Script References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/b1050d27-217f-4b42-a5d4-c1582aa50215)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OCC_1_1.yaml

### Additional Info:
**Raised Test plan Issue for the same** :- https://github.com/CHIP-Specifications/chip-test-plans/issues/2891
Once the Test plan is fixed script has to be updated

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30869](https://github.com/project-chip/connectedhomeip/pull/30869) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
