### ISSUE TITLE
[TC-OO-1.1] Script has to be updated as per Spec. 

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#73]
### Description:
- [ ] Step 2 - In Spec Cluster Revision value has been updated from **5** to **6** . So Script has to be updated as per Spec. 

### Spec References:
 ![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/58d458de-d32b-44dd-90c1-ae220cc3e2d6)
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OnOff.adoc#1-revision-history

### Yaml- Script References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/1477b097-349c-432d-8e15-c2fe53f2ded7)
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OO_1_1.yaml

- [ ]  Step 6a - **On** and **Toggle** commands conformance has been changed from **Mandatory** to **!OFFONLY**. So AcceptedCommandList should list these commands in Feature dependent list.

### Spec References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/05814fd6-9fcc-44ff-9509-e1e31333f1c1)

- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OnOff.adoc#7-commands

### Yaml- Script References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/97d4074f-aca9-4e18-a5f0-80d2f6de272e)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_OO_1_1.yaml

- [ ] Step 3 - Script missed to validate the **OffOnly** feature in FeatureMap list.

### Steps to reproduce:
Steps 2, 6a

### Additional Info:
**Raised Test Plan Issues For same:** https://github.com/CHIP-Specifications/chip-test-plans/issues/3531
Once the Test plan is fixed script has to be updated

**Comment by raul-marquez-csa** [comment]
The steps are outdated in general as per the test plan verification
https://docs.google.com/spreadsheets/d/1kzwnEJgffWxR3FSGWZnPz_kDshwSZf3z3fR1oNlgnSw/edit#gid=2077263526

**Comment by Ashwinigrl** [comment]
Issue fixed
