### ISSUE TITLE
[TC-G-2.2, 2.3] Script has to be updated as per Test plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#75]
### Description:

**Script has to be updated for below Steps.**

 **TC-G-2.2** 
- [ ] Steps 23, 24  are newly added to the Test plan. 

 **TC-G-2.3** 
- [ ] Steps 19b is newly added to the Test plan. 
- [ ] In Step 21a Test step label  has been updated. 

### Steps to reproduce:
TC-G-2.2 - Steps 23, 24
TC-G-2.3 - Steps 19b

### Test Plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Groups.adoc#422-tc-g-22-commands---addgroup-viewgroup-removegroup-removeallgroups-dut-server

### Yaml- Script References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_G_2_2.yaml
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_G_2_3.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30869](https://github.com/project-chip/connectedhomeip/pull/30869) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
@manjunath-grl TC-G-2.3 -  In Step 21a Test step label has to be updated as per Test plan.

**Comment by Ashwinigrl** [comment]
Issue Fixed
