### ISSUE TITLE
[TC-BIND-2.1] - `MCORE.ROLE.CONTROLLER` and `!MCORE.DT_SW_COMP` High level PICS has to be added in Script.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#76]
### Description:
[TC-BIND-2.1] - `MCORE.ROLE.CONTROLLER` and `!MCORE.DT_SW_COMP` High level PICS has to be added in Script as per Test plan.

### Test plan Reference:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/b844cf0f-e77b-46e1-b462-e458d4fc8336)

- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/binding.adoc#pics-1

## Yaml-Script References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/126d5857-b680-4432-93c5-0d7292e1c24e)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_BIND_2_1.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30869](https://github.com/project-chip/connectedhomeip/pull/30869) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
