### ISSUE TITLE
[Matter1.2 TH] TC-SC-5.2 Failure due to Unsupported Group Cluster

### ISSUE THREAD

**Issue by ZainZhongUL** [project-chip/matter-test-scripts#77]
## Summary Title: 
TC-SC-5.2 Failure due to Unsupported Group Cluster

## Description:
The yaml test script seems to not check PICS in steps 4, 5, 8, and 10 which require the Group Cluster to be supported.

## Additional Info:
The DUT does not support the group cluster. This issue is similar to GitHub issue #3286, which was closed and fixed by #3313. 

Matter v1.2 test plan & spec
Version: TH Fall2023
Sha: 3f84bff5
PICS version: see attached.

[UI_Test_Run_2023_12_11_14_39_20.log](https://github.com/project-chip/matter-test-scripts/files/13631993/UI_Test_Run_2023_12_11_14_39_20.log)

[Group Communication.zip](https://github.com/project-chip/matter-test-scripts/files/13632004/Group.Communication.zip)

**Comment by manjunath-grl** [comment]
@ZainZhongUL fixed in PR [30951](https://github.com/project-chip/connectedhomeip/pull/30951) please verify it and close the ticket.
