### ISSUE TITLE
[TC-BRBINFO-2.1] Script has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#78]
## Description:

- **TC-BRBINFO-2.1:** Step 62 and 63 has been added newly in test plan. So Yaml script has to be updated for the same.

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30951](https://github.com/project-chip/connectedhomeip/pull/30951) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved

**Comment by KishokG** [comment]
Issue resolved
