### ISSUE TITLE
[TC-CC-8.1] Test Case failing due to CurrentHue attribute value mismatch

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#8]
From chip-test-scripts created by [Ashwinigrl](https://github.com/Ashwinigrl): CHIP-Specifications/chip-test-scripts#657  

### Description:
[TC-CC-8.1] - Steps 2d and 2e failing due to CurrentHue attribute value mismatch.

### Steps to reproduce:
Step 2d, 2e

### Screen Shot:
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/98016634/0f501524-155e-4a2c-a7da-38ee0b8b6706)

### Logs:
[TC-CC-8.1.log](https://github.com/CHIP-Specifications/chip-test-scripts/files/12669841/TC-CC-8.1.log)

### Additional Info:
DUT : All-clusters-app
Endpoint : 1
PICS used :
[Color Control Cluster Test Plan.zip](https://github.com/CHIP-Specifications/chip-test-scripts/files/12669870/Color.Control.Cluster.Test.Plan.zip)
[On-Off Cluster Test Plan.zip](https://github.com/CHIP-Specifications/chip-test-scripts/files/12669871/On-Off.Cluster.Test.Plan.zip)

### Environment :
Version: TH Fall2023
Sha: 27090a17

**Comment by raju-apple** [comment]
@Ashwinigrl is this still happening on the latest TH release ?

**Comment by raju-apple** [comment]
@raju-apple TC-CC-8.1 Test case is verified with latest TH image(Version: TH Fall2023 Sha: 3f84bff5) still facing the same issue.

**PICS file used:**
[Color Control Cluster Test Plan.txt](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039324/Color.Control.Cluster.Test.Plan.txt)
[On-Off Cluster Test Plan .txt](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039325/On-Off.Cluster.Test.Plan.txt)

**Reference log :**
[TC-CC-8.1.pdf](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039110/TC-CC-8.1.pdf)
[CC_8-1_2023_10_18_17_44_52.log](https://github.com/CHIP-Specifications/chip-test-scripts/files/13039109/CC_8-1_2023_10_18_17_44_52.log)

**Endpoint used :** 1

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30869](https://github.com/project-chip/connectedhomeip/pull/30869) please verify and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed in latest **TH Version**: main - dev **Sha**: f17efc4.
Hence closing this Issue
