### ISSUE TITLE
[CNET] Script has to be updated as per test plan

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#82]
## Description:

**Commissioning related Precondition step has to be removed from the script as it is not necessary for below test cases:**

- TC-CNET-4.1
- TC-CNET-4.2
- TC-CNET-4.4
- TC-CNET-4.5
- TC-CNET-4.6
- TC-CNET-4.9
- TC-CNET-4.10
- TC-CNET-4.11
- TC-CNET-4.15
- TC-CNET-4.16
- TC-CNET-4.22

**TC-CNET-4.5:**

- In step 1, `breadcrumb` has to be changed to `Breadcrumb` in script.

**UI Snapshot:**
![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/620b48cb-2cd8-4a8e-82b7-62e476251bed)

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [30951](https://github.com/project-chip/connectedhomeip/pull/30951) please verify it and close the ticket.

**Comment by KishokG** [comment]
@manjunath-grl 

**Commissioning related Precondition step has to be removed from the script as it is not necessary for below test cases:**

- TC-CNET-4.1
- TC-CNET-4.2
- TC-CNET-4.4
- TC-CNET-4.5
- TC-CNET-4.6
- TC-CNET-4.9
- TC-CNET-4.10
- TC-CNET-4.11
- TC-CNET-4.15
- TC-CNET-4.16
- TC-CNET-4.22

**Comment by raul-marquez-csa** [comment]
> * TC-CNET-4.1
> * TC-CNET-4.2

TC-CNET-4.1 and TC-CNET-4.2 didn't contain a commissioning precondition step but were removed for the rest in the list.

**Comment by raul-marquez-csa** [comment]
PR
https://github.com/project-chip/connectedhomeip/pull/32659

**Comment by KishokG** [comment]
Issue fixed
