### ISSUE TITLE
[TC-SWTCH-2.2, 3.2] Manual Yaml script has to be updated as per VS Document

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#84]
### Description:
**TC-SWTCH-2.2:**
- [ ] Step 2f, 2g CurrentPosition attribute log is missing in Script.
- [ ] Step 2f Comment has to be updated as per VS document.

**TC-SWTCH-3.2:**
- [ ] `MCORE.IDM.C.SubscribeEvent` High level PICS has to be added in Script.
- [ ] Log and comments has to be updated as per VS document for all Steps.

### Yaml References:
 - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SWTCH_3_2.yaml
 - https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_SWTCH_2_2.yaml

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
