### ISSUE TITLE
[TC-CC-3.3] Step 2e is skipping in UI, Because of  `&&`  operator is missing in between the PICS.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#86]
### Description:
 **TC-CC-3.3** 
 Step 2e is skipping in UI, Because in script `&& ` operator is missing  in between the `CC.S.A0000` and `PICS_SKIP_SAMPLE_APP` PICS. 

### Steps to reproduce:
Step 2e

### Logs:
[TC-CC-3.3.log](https://github.com/project-chip/matter-test-scripts/files/13659046/TC-CC-3.3.log)

### Screen shot:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/36960e2a-7fac-4916-8ca8-9eefaae78647)

### Yaml References:
![image](https://github.com/project-chip/matter-test-scripts/assets/98016634/2794054d-10e5-4967-a261-8a8f8825df67)

- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CC_3_3.yaml

### Additional Info:
TH Version: main - dev
 Sha: f17efc4

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [30951](https://github.com/project-chip/connectedhomeip/pull/30951) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
