### ISSUE TITLE
[TC-REFALM-2.2]Semi Auto  - Step 6 - comment has to be updated as per VS

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#88]
## Description:
[TC-REFALM-2.2] - Step 6 comment should be updated as per Verification step
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/b804b9d8-78fe-449b-9d49-d1a43d99289f)
![image](https://github.com/project-chip/matter-test-scripts/assets/95841834/6cc0ef44-6e8a-4f19-996e-d1824c7195fc)

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_REFALM_2_2.yaml

**Comment by manjunath-grl** [comment]
@Rajashreekalmane fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
issue resolved in latest Image, hence closing this issue.
