### ISSUE TITLE
[DRLK] Script has to be updated as per test plan

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#9]
From chip-test-scripts created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-test-scripts#661  

**Description:**

-  **TC-DRLK-2.10:** Step 5a and 5e command has to be updated.
- **TC-DRLK-2.1:** Step 2b, step number has to be updated in script as per test plan.

**Script Snapshot:**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/133193761/88f4432e-1b7b-43fc-a643-156362fb716f)

**Test plan Reference:**
![image](https://github.com/CHIP-Specifications/chip-test-scripts/assets/133193761/bba04cd5-19a7-491d-858d-7f7ed7464b74)

**Comment by raju-apple** [comment]
@KishokG fixed in PR [29747](https://github.com/project-chip/connectedhomeip/pull/29747) please verify and close the ticket.

**Comment by raju-apple** [comment]
@Survensa looks like @KishokG is not part of the repo yet

**Comment by KishokG** [comment]
@raju-apple Since this issue was raised from your Id. I can't able to close this issue.
Issue is resolved so please close the issue.
