### ISSUE TITLE
[Matter1.2 TH] TC-I-2.2, Step1b and Step6a - Script should be updated as TestPlan

### ISSUE THREAD

**Issue by panshaoem** [project-chip/matter-test-scripts#90]
## Description:
![image](https://github.com/project-chip/matter-test-scripts/assets/103939095/20b4fe6f-7169-4d4d-8f2e-05e76b58d620)
<img width="444" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/0e56de9c-05e9-451d-b53a-c7c4992a2d34">
    The test script should not verify whether the device has entered the identification state at the first pop-up window before Step2a, but should prompt the tester to check the value of IdentifyType from the LOG and record it. This is because at this time, TH has not even sent the identify command to the device, so the device will not take any action.
<img width="431" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/497c77f9-af92-4b5b-8503-227887ce2e6b">
The test script should add a pop-up window at Step6a to verify whether the device has entered the identification state.

**Comment by manjunath-grl** [comment]
@panshaoem fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.
