### ISSUE TITLE
 [Matter1.2 TH] TC-IDM-4.2, Step 2 - Script should be updated as TestPlan

### ISSUE THREAD

**Issue by panshaoem** [project-chip/matter-test-scripts#91]
## Description:
[TC-IDM-4.2], Step 2 - Script should be updated as TestPlan

<img width="874" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/957fcda2-8108-42cd-a760-904a33988c63">
<img width="501" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/110dabbc-50c3-4138-a567-aecf638afe6d">

**Comment by manjunath-grl** [comment]
@panshaoem fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.
