### ISSUE TITLE
[Matter1.2 TH] TC-ACL-2.2, Step 3 - Should read every Endpoint except 0

### ISSUE THREAD

**Issue by panshaoem** [project-chip/matter-test-scripts#92]
## Summary Title: 
[Matter1.2 TH] TC-ACL-2.2, Step 3 - Should read every Endpoint except 0

## Description:
The DUT sometimes has more than one endpoint besides 0, such as chip-all-clusters-app, which has Endpoint_1 and Endpoint_2. However, the test script seems to only read Endpoint_1, which does not match the TestPlan.
<img width="448" alt="image" src="https://github.com/project-chip/matter-test-scripts/assets/103939095/215b6b8c-63a4-45aa-852c-c62c8cfbc5b0">

## Logs:
[TC-ACL-2.2-ALL-CLUSTER-APP.txt](https://github.com/project-chip/matter-test-scripts/files/13672156/TC-ACL-2.2-ALL-CLUSTER-APP.txt)

[TC-ACL-2.2-TestHarness.log](https://github.com/project-chip/matter-test-scripts/files/13672160/TC-ACL-2.2-TestHarness.log)

**Comment by cecille** [comment]
Just FYI, I'm not sure this is do-able in yaml right now. The current implementation is bizzare.

**Comment by cecille** [comment]
Here - use this: https://github.com/project-chip/connectedhomeip/pull/31049
