### ISSUE TITLE
[TC-S-2.3] Script has to be updated as per Test plan 

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#93]
### Description:

- [ ] Step 2b, 3b PICS has to be updated as per Test plan.
- [ ] Step 2a, 2b - In Reference command GroupId, SceneId and Transition time values has to be updated as per Test label.

### Steps to reproduce:
Steps 2a, 2b, 3b

### Yaml References:
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_S_2_3.yaml

### Test plan References:
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#tc-s-2-3-secondary-functionality-with-dut_server

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
