### ISSUE TITLE
[TC-S-3.1] Yaml Script has to be implemented for newly added Test case

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/matter-test-scripts#94]
### Description:
 **TC-S-3.1** Test case is newly added to the Test plan, So Yaml Script has to be implemented for this newly added Test case.

### Test Plan References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc#tc-s-3-1-functionality-with-dut_client

**Comment by manjunath-grl** [comment]
@Ashwinigrl fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by Ashwinigrl** [comment]
Issue Fixed
