### ISSUE TITLE
TC-APPOBSERVER-1.13 -  New TC needs to be added to the script

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#95]
Description :
New test case, TC-APPOBSERVER-1.13, has recently been added to the test plan. Therefore, it is necessary to update the script to include support for this new test case

Test-Plan reference :
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-appobserver-1-13-global-attributes-content-app-observer-cluster-dut-as-server

**Comment by manjunath-grl** [comment]
@Rajashreekalmane Added new test in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by Rajashreekalmane** [comment]
Issue has been resolved in latest IMAGE
