### ISSUE TITLE
[DRLK] High level PICS has to be updated as per test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#96]
## Description:

High level PICS has to be updated as per latest test plan for below test cases:

- TC-DRLK-2.5
- TC-DRLK-2.7

**Script Reference:**
![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/fbbd65e3-1f40-4440-997c-a586a2415a7b)

**Test plan Reference:**
![image](https://github.com/project-chip/matter-test-scripts/assets/133193761/27ce0fc4-e8f6-4968-9ad9-f22fabc9d4e4)

**Comment by manjunath-grl** [comment]
@KishokG fixed in PR [31060](https://github.com/project-chip/connectedhomeip/pull/31060) please verify it and close the ticket.

**Comment by KishokG** [comment]
Issue resolved
