### ISSUE TITLE
[Matter1.2 TH] TC-WNCV-3.1, Step3a2 to Step3a6 - The script attempts read and write operations on the “Unit Testing Cluster”

### ISSUE THREAD

**Issue by panshaoem** [project-chip/matter-test-scripts#97]
## Description:
When testing the product with Device Type as Window Covering (0x0202), it was found that these steps would return UNSUPPORTED_CLUSTER (0xC3), as shown in the figure. How should these steps be handled? Does the DUT have to support the “Unit Testing Cluster”?
![image](https://github.com/project-chip/matter-test-scripts/assets/103939095/928dc629-0929-4143-ab50-fe173e52a287)

## Additional Info:
yaml: https://github.com/project-chip/connectedhomeip/blob/v1.2.0.1/src/app/tests/suites/certification/Test_TC_WNCV_3_1.yaml
PICS:  [Window Covering Cluster Test Plan.txt](https://github.com/project-chip/matter-test-scripts/files/13715090/Window.Covering.Cluster.Test.Plan.txt)

This also appears in TC-WNCV-3.2.
https://github.com/project-chip/connectedhomeip/blob/v1.2.0.1/src/app/tests/suites/certification/Test_TC_WNCV_3_2.yaml

**Comment by manjunath-grl** [comment]
@panshaoem fixed in PR [31365](https://github.com/project-chip/connectedhomeip/pull/31365) please verify and close the ticket.
