### ISSUE TITLE
[TC-SWTCH-3.2] Step3a - Commission DUT to TH

### ISSUE THREAD

**Issue by lion6420** [project-chip/matter-test-scripts#99]
## Description:
   I think it may not an issue, just want to confirm.
   In this case, DUT and TH had been commissioned in previous step. So, step3a is just an information, telling TH should be pairing to DUT's fabric, not necessary to pair again right?

#### Test_TC_SWTCH_3_2.yaml

```
- label:
          "Step 3a: Commission DUT to TH. Use client mechanism to set it up so
          switch state can be observed (e.g. UI shows state of switch) and/or
          other device is controlled (e.g. light on same fabric gets controlled
          by the switch  TH has to simulate that light). While commissioning and
          configuring, TH records and reacts to the messages relating to the
          switch functionality detailed in the steps below. The order of the
          messages received may be different from the order of the sub-steps
          3b..3d below."
      PICS: SWTCH.C.F01
      verification: |

      disabled: true
```

**Comment by manjunath-grl** [comment]
@lion6420, there is no need to recommission again. This information is solely for commissioning the DUT based on PICS. If commissioning occurred prior to the test case, there is no need for re-commissioning the TH and DUT.

**Comment by lion6420** [comment]
@manjunath-grl Thanks for your explanation, I will close the issue.
